// Cycle 3 (CM1, CM2, 6e) : le programme en vigueur à la rentrée 2020 (annexe 2), résumé au grain d'une mission ; pour
// les sciences et la technologie, le programme en vigueur à la rentrée 2023 (champ `source` des domaines).
// Les libellés sont des résumés fidèles du texte officiel ; le texte fait foi (page du PDF indiquée).
import type { ProgrammeDomaine, ProgrammeEntry } from './types';

export const DOMAINES_C3: readonly ProgrammeDomaine[] = [
  { id: 'c3-fr-oral', cycle: 3, discipline: 'french', title: 'Langage oral', page: 10 },
  { id: 'c3-fr-lecture', cycle: 3, discipline: 'french', title: 'Lecture et compréhension de l’écrit', page: 14 },
  { id: 'c3-fr-ecriture', cycle: 3, discipline: 'french', title: 'Écriture', page: 17 },
  { id: 'c3-fr-langue', cycle: 3, discipline: 'french', title: 'Étude de la langue (grammaire, orthographe, lexique)', page: 21 },
  { id: 'c3-fr-culture', cycle: 3, discipline: 'french', title: 'Culture littéraire et artistique', page: 25 },
  { id: 'c3-ma-nombres', cycle: 3, discipline: 'maths', title: 'Nombres et calculs', page: 91 },
  { id: 'c3-ma-grandeurs', cycle: 3, discipline: 'maths', title: 'Grandeurs et mesures', page: 94 },
  { id: 'c3-ma-espace', cycle: 3, discipline: 'maths', title: 'Espace et géométrie', page: 96 },
  { id: 'c3-en-ecouter', cycle: 3, discipline: 'english', title: 'Langues vivantes : écouter et comprendre', page: 33 },
  { id: 'c3-en-lire', cycle: 3, discipline: 'english', title: 'Langues vivantes : lire et comprendre', page: 34 },
  { id: 'c3-en-parler', cycle: 3, discipline: 'english', title: 'Langues vivantes : parler en continu', page: 35 },
  { id: 'c3-en-ecrire', cycle: 3, discipline: 'english', title: 'Langues vivantes : écrire', page: 36 },
  { id: 'c3-en-dialoguer', cycle: 3, discipline: 'english', title: 'Langues vivantes : réagir et dialoguer', page: 37 },
  { id: 'c3-en-culture', cycle: 3, discipline: 'english', title: 'Langues vivantes : connaissances culturelles', page: 38 },
  { id: 'c3-en-langue', cycle: 3, discipline: 'english', title: 'Langues vivantes : grammaire et phonologie', page: 39 },
  // Histoire et géographie : pages et libellés vérifiés dans le PDF cité par sources.ts (7 octobre 2026). Seule la
  // classe de 6e est résumée : le CM1 et le CM2 ne sont pas dans l'application.
  { id: 'c3-hg-temps', cycle: 3, discipline: 'history-geography', title: 'Histoire et géographie : se repérer dans le temps', page: 67 },
  { id: 'c3-hg-espace', cycle: 3, discipline: 'history-geography', title: 'Histoire et géographie : se repérer dans l’espace', page: 67 },
  { id: 'c3-hg-demarches', cycle: 3, discipline: 'history-geography', title: 'Histoire et géographie : raisonner, comprendre un document, pratiquer différents langages', page: 67 },
  { id: 'c3-hg-histoire', cycle: 3, discipline: 'history-geography', title: 'Histoire, classe de sixième', page: 71 },
  { id: 'c3-hg-geographie', cycle: 3, discipline: 'history-geography', title: 'Géographie, classe de sixième', page: 75 },
  // Sciences et technologie, découpées en trois disciplines comme au collège (choix C du mainteneur, 5 octobre 2026) :
  // SVT (le vivant, la Terre peuplée par des êtres vivants), physique-chimie (matière, mouvement, énergie,
  // information), technologie (les objets techniques au cœur de la société). Le texte en vigueur en 6e est celui du
  // BO n° 25 du 22 juin 2023, qui a remplacé cette partie du PDF de 2020 : libellés et pages sont lus dans le
  // programme du cycle 3 en vigueur à la rentrée 2023 (source c3-2023, 7 octobre 2026). Les compétences travaillées
  // sont communes aux trois disciplines (page 80) : chaque discipline reprend celles qu'elle travaille.
  { id: 'c3-sv-demarches', cycle: 3, discipline: 'life-earth-sciences', title: 'Sciences et technologie : compétences travaillées (SVT)', page: 80, source: 'c3-2023' },
  { id: 'c3-sv-vivant', cycle: 3, discipline: 'life-earth-sciences', title: 'Le vivant, sa diversité et les fonctions qui le caractérisent', page: 87, source: 'c3-2023' },
  { id: 'c3-sv-terre', cycle: 3, discipline: 'life-earth-sciences', title: 'La Terre, une planète peuplée par des êtres vivants', page: 95, source: 'c3-2023' },
  { id: 'c3-pc-demarches', cycle: 3, discipline: 'physics-chemistry', title: 'Sciences et technologie : compétences travaillées (physique-chimie)', page: 80, source: 'c3-2023' },
  { id: 'c3-pc-matiere', cycle: 3, discipline: 'physics-chemistry', title: 'Matière, mouvement, énergie, information', page: 81, source: 'c3-2023' },
  { id: 'c3-te-demarches', cycle: 3, discipline: 'technology', title: 'Sciences et technologie : compétences travaillées (technologie)', page: 80, source: 'c3-2023' },
  { id: 'c3-te-objets', cycle: 3, discipline: 'technology', title: 'Les objets techniques au cœur de la société', page: 91, source: 'c3-2023' },
];

// Attendus de fin de cycle, cités (raccourcis) une fois pour ne pas les répéter à chaque entrée.
const FR_LIRE = 'Lire, comprendre et interpréter un texte littéraire adapté à son âge et réagir à sa lecture';
const FR_DOCS = 'Lire et comprendre des textes et des documents (textes, tableaux, graphiques, schémas, diagrammes, images) pour apprendre dans les différentes disciplines';
const FR_ORAL_ECRIT = 'Maîtriser les relations entre l’oral et l’écrit';
const FR_ACCORDS = 'Maîtriser les accords dans le groupe nominal, entre le verbe et son sujet dans les cas simples, et l’accord de l’attribut';
const FR_SENS = 'Raisonner pour analyser le sens des mots en contexte et en prenant appui sur la morphologie';
const FR_PHRASE = 'Être capable de repérer les principaux constituants d’une phrase simple et complexe';
const FR_ORTHO_LEX = 'Acquérir l’orthographe lexicale';
const MA_N1 = 'Utiliser et représenter les grands nombres entiers, des fractions simples, les nombres décimaux';
const MA_N2 = 'Calculer avec des nombres entiers et des nombres décimaux';
const MA_N3 = 'Résoudre des problèmes en utilisant des fractions simples, les nombres décimaux et le calcul';
const MA_G1 = 'Comparer, estimer, mesurer des grandeurs géométriques avec des nombres entiers et des nombres décimaux : longueur (périmètre), aire, volume, angle';
const MA_G2 = 'Utiliser le lexique, les unités, les instruments de mesures spécifiques de ces grandeurs';
const MA_G3 = 'Résoudre des problèmes impliquant des grandeurs (géométriques, physiques, économiques) en utilisant des nombres entiers et des nombres décimaux';
const MA_E1 = '(Se) repérer et (se) déplacer dans l’espace en utilisant ou en élaborant des représentations';
const MA_E2 = 'Reconnaître, nommer, décrire, reproduire, représenter, construire des figures et solides usuels';
const MA_E3 = 'Reconnaître et utiliser quelques relations géométriques (alignement, perpendicularité, parallélisme, égalité de longueurs, symétrie, agrandissement et réduction)';
const EN_ECOUTER = 'A1 : comprendre des mots familiers et des expressions très courantes sur soi, sa famille et son environnement immédiat ; A2 : comprendre une intervention brève si elle est claire et simple';
const EN_LIRE = 'A1 : comprendre des mots familiers et des phrases très simples ; A2 : comprendre des textes courts et simples';
const EN_PARLER = 'A1 : utiliser des expressions et des phrases simples pour parler de soi et de son environnement immédiat ; A2 : produire en termes simples des énoncés sur les gens et les choses';
const EN_ECRIRE = 'A1 : copier un modèle écrit, écrire un court message et renseigner un questionnaire simple ; A2 : produire des énoncés simples et brefs';
const EN_DIALOGUER = 'A1 : communiquer de façon simple si l’interlocuteur répète ou reformule ; A2 : interagir de façon simple et reformuler son propos pour s’adapter à l’interlocuteur';
const EN_CULTURE = 'Identifier quelques grands repères culturels de l’environnement quotidien des élèves du même âge dans les pays ou régions étudiés';
const EN_GRAMMAIRE = 'Avoir un contrôle limité de quelques structures et formes grammaticales simples appartenant à un répertoire mémorisé';
const EN_PHONO = 'Reconnaître et reproduire de manière intelligible les sons, l’accentuation, les rythmes et les courbes intonatives propres à la langue';

const HG_TEMPS = 'Se repérer dans le temps : construire des repères historiques';
const HG_ESPACE = 'Se repérer dans l’espace : construire des repères géographiques';
const HG_DOC = 'Comprendre un document';
const HG_LANGAGES = 'Pratiquer différents langages en histoire et en géographie';
const HG_RAISONNER = 'Raisonner, justifier une démarche et les choix effectués';
const HG_H1 = 'Thème 1 : la longue histoire de l’humanité et des migrations';
const HG_H2 = 'Thème 2 : récits fondateurs, croyances et citoyenneté dans la Méditerranée antique au Ier millénaire avant J.-C.';
const HG_H3 = 'Thème 3 : l’empire romain dans le monde antique';
const HG_G1 = 'Thème 1 : habiter une métropole';
const HG_G2 = 'Thème 2 : habiter un espace de faible densité';
const HG_G3 = 'Thème 3 : habiter les littoraux';
const HG_G4 = 'Thème 4 : le monde habité';

// Sciences et technologie (programme du cycle 3 en vigueur à la rentrée 2023) : les compétences travaillées (page 80),
// puis les attendus de fin de cycle de chaque partie, réunis quand une compétence en couvre plusieurs.
const ST_DEMARCHE = 'Pratiquer des démarches scientifiques et technologiques';
const ST_CONCEVOIR = 'Concevoir, créer, réaliser';
const ST_LANGAGES = 'Pratiquer des langages';
const ST_NUMERIQUE = 'Mobiliser des outils numériques';
const ST_RESPONSABLE = 'Adopter un comportement éthique et responsable';
const ST_SITUER = 'Se situer dans l’espace et dans le temps';
const ST_CRITIQUE = 'Faire preuve d’esprit critique';
const PC_MATIERE = 'Décrire un échantillon de matière à l’aide du vocabulaire scientifique et des grandeurs physiques : masse, volume ; caractériser la diversité de la matière et de ses transformations à l’échelle macroscopique';
const PC_MATERIAUX = 'Utiliser les propriétés physiques des matériaux pour les classer, notamment à des fins de tri';
const PC_MOUVEMENT = 'Décrire un mouvement en précisant le point de vue ; caractériser un mouvement par des mesures';
const PC_ENERGIE = 'Identifier les formes d’énergie mises en jeu dans un dispositif de conversion d’énergie ; rechercher et exploiter des informations sur les ressources en énergie et leur utilisation, en exerçant son esprit critique';
const PC_OMBRES = 'Interpréter la formation d’ombres, en particulier dans le contexte du système Soleil-Terre-Lune';
const PC_CIRCUIT = 'Mettre en œuvre des circuits électriques à une boucle en respectant des consignes de sécurité';
const PC_SIGNAL = 'Identifier des signaux de natures différentes et citer des applications dans lesquelles un signal permet de transmettre une information';
const SV_PANORAMA = 'Caractériser la richesse, l’unité et la diversité actuelle et passée du vivant ; classer les organismes et établir les liens de parenté';
const SV_ALIMENTS = 'Expliquer le rôle des aliments pour le fonctionnement de l’organisme ; identifier les principes des technologies mises en œuvre pour transformer et conserver les aliments';
const SV_CYCLE = 'Décrire le cycle de vie d’une plante à fleurs et celui d’un animal ; décrire les changements pubertaires associés à la capacité de se reproduire ; distinguer la dimension biologique de la sexualité humaine de ses autres dimensions';
const SV_TERRE = 'Identifier l’activité de la planète Terre et ses conséquences ; décrire les conditions de la vie terrestre ; différencier la météorologie du climat ; construire une argumentation scientifique pour expliquer le réchauffement climatique actuel';
const SV_ECOSYSTEME = 'Décrire un écosystème et caractériser ses interactions ; mettre en évidence la place et l’interdépendance des êtres vivants dans un réseau trophique ; caractériser les conséquences d’une action humaine sur un écosystème';
const TE_BESOIN = 'Identifier un besoin exprimé par la société et lui associer des objets techniques ; distinguer un objet technique d’un objet naturel ; repérer les évolutions des objets techniques selon leur contexte d’utilisation ; citer des objets détournés de leur usage initial';
const TE_FONCTIONNEMENT = 'Distinguer besoins, fonctions techniques et solutions technologiques ; décrire un objet technique par un schéma (son fonctionnement) et un croquis (ce que l’on observe)';
const TE_CONCEPTION = 'Décrire et pratiquer la démarche technologique dans le cadre d’un projet ; participer à un travail collectif ; identifier les liens entre des choix de conception et leurs effets sur les étapes du cycle de vie d’un objet technique';
const TE_PROGRAMMATION = 'Repérer la chaîne d’information et la chaîne d’action d’un objet programmable ; programmer un objet technique pour obtenir un comportement attendu';

export const ENTRIES_C3 = [
  // ---------- Français ----------
  { id: 'c3.fr.oral.comprendre-s-exprimer', cycle: 3, discipline: 'french', domaine: 'c3-fr-oral', attendu: 'Écouter pour comprendre un message oral ; parler en prenant en compte son auditoire ; participer à des échanges', competence: 'Langage oral : écouter, dire, débattre, présenter', page: 10 },
  { id: 'c3.fr.lecture.fluidite', cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_LIRE, competence: 'Lire avec fluidité : mémoriser la lecture de mots fréquents et irréguliers, automatiser le décodage, respecter les groupes syntaxiques et la ponctuation', page: 15 },
  { id: 'c3.fr.lecture.explicite', cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_LIRE, competence: 'Comprendre un texte : repérer les informations explicites, les personnages, les lieux, les actions, les repères temporels', page: 15 },
  { id: 'c3.fr.lecture.implicite', cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_LIRE, competence: 'Repérer l’implicite et les liens logiques d’un texte ; justifier son interprétation en s’appuyant sur le texte', page: 15 },
  { id: 'c3.fr.lecture.reprises', cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_LIRE, competence: 'Être vigilant aux reprises nominales et pronominales : savoir de qui ou de quoi on parle', page: 16 },
  { id: 'c3.fr.lecture.lexique-contexte', cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_LIRE, competence: 'Élucider le sens d’un mot inconnu par le contexte, la morphologie ou le dictionnaire', page: 15 },
  { id: 'c3.fr.lecture.genres', cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_LIRE, competence: 'Identifier les principaux genres littéraires (conte, roman, poésie, fable, nouvelle, théâtre) et leurs caractéristiques', page: 15 },
  { id: 'c3.fr.lecture.documents', cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_DOCS, competence: 'Comprendre un document composite : mettre en relation texte, image, schéma, tableau ou graphique ; identifier la nature et la source du document', page: 16 },
  { id: 'c3.fr.ecriture.rediger', cycle: 3, discipline: 'french', domaine: 'c3-fr-ecriture', attendu: 'Écrire un texte d’une à deux pages adapté à son destinataire ; après révision, obtenir un texte organisé et cohérent', competence: 'Écriture : rédiger des écrits variés, réviser et améliorer son texte', page: 17 },
  { id: 'c3.fr.langue.phonemes-graphemes', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ORAL_ECRIT, competence: 'Maîtriser l’ensemble des phonèmes du français et des graphèmes associés ; consolider le décodage', page: 21 },
  { id: 'c3.fr.langue.genre-nombre', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ORAL_ECRIT, competence: 'Connaître les marques du genre et du nombre, à l’oral et à l’écrit (noms, déterminants, adjectifs, pronoms, verbes)', page: 21 },
  { id: 'c3.fr.langue.homophonie', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ORAL_ECRIT, competence: 'Prendre conscience des homophones lexicaux et grammaticaux et les distinguer en contexte', page: 22 },
  { id: 'c3.fr.langue.nature-fonction', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_PHRASE, competence: 'Comprendre et maîtriser les notions de nature (classe grammaticale) et de fonction', page: 22 },
  { id: 'c3.fr.langue.sujet', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_PHRASE, competence: 'Identifier le sujet, y compris composé de plusieurs noms ou inversé', page: 22 },
  { id: 'c3.fr.langue.complements', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_PHRASE, competence: 'Différencier les compléments : COD, COI, compléments circonstanciels de temps, de lieu et de cause', page: 22 },
  { id: 'c3.fr.langue.attribut-gn', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_PHRASE, competence: 'Identifier l’attribut du sujet ; analyser le groupe nominal : épithète et complément du nom', page: 22 },
  { id: 'c3.fr.langue.classes-de-mots', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_PHRASE, competence: 'Différencier les classes de mots : déterminants possessifs et démonstratifs, pronom personnel objet, adverbe, préposition, conjonctions de coordination et de subordination', page: 22 },
  { id: 'c3.fr.langue.types-formes', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_PHRASE, competence: 'Connaître les trois types de phrases (déclarative, interrogative, impérative) et les formes négative et exclamative', page: 22 },
  { id: 'c3.fr.langue.phrase-complexe', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_PHRASE, competence: 'Différencier phrase simple et phrase complexe ; repérer juxtaposition, coordination et subordination', page: 22 },
  { id: 'c3.fr.langue.accord-gn', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ACCORDS, competence: 'Connaître la notion de groupe nominal et d’accord au sein du groupe nominal (déterminant, nom, adjectif)', page: 23 },
  { id: 'c3.fr.langue.accord-sujet-verbe', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ACCORDS, competence: 'Maîtriser l’accord du verbe avec son sujet, y compris inversé', page: 23 },
  { id: 'c3.fr.langue.attribut-participe-etre', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ACCORDS, competence: 'Maîtriser l’accord de l’attribut avec le sujet et du participe passé avec être (cas les plus usuels)', page: 23 },
  { id: 'c3.fr.langue.reconnaitre-verbe', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ACCORDS, competence: 'Reconnaître le verbe ; connaître les trois groupes ; distinguer temps simples et temps composés ; comprendre la notion de participe passé', page: 23 },
  { id: 'c3.fr.langue.temps-a-memoriser', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ACCORDS, competence: 'Mémoriser le présent, l’imparfait, le futur, le passé simple, le passé composé, le plus-que-parfait, le conditionnel présent et l’impératif présent pour être, avoir, les verbes des 1er et 2e groupes et faire, aller, dire, venir, pouvoir, voir, vouloir, prendre', page: 23 },
  { id: 'c3.fr.langue.finales-en-e', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ACCORDS, competence: 'Distinguer les finales verbales en /E/ (é, er, ez) par la procédure de remplacement', page: 23 },
  { id: 'c3.fr.langue.derivation-composition', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_SENS, competence: 'Comprendre la formation des mots complexes par dérivation (préfixe, radical, suffixe) et par composition', page: 24 },
  { id: 'c3.fr.langue.racines', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_SENS, competence: 'Connaître le sens des principaux préfixes ; découvrir des racines latines et grecques', page: 24 },
  { id: 'c3.fr.langue.familles-champ-lexical', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_SENS, competence: 'Mettre en réseau des mots : familles de mots, champ lexical', page: 24 },
  { id: 'c3.fr.langue.synonymie', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_SENS, competence: 'Connaître les notions de synonymie, d’antonymie, d’homonymie et de polysémie', page: 24 },
  { id: 'c3.fr.langue.mots-invariables', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ORTHO_LEX, competence: 'Mémoriser l’orthographe des mots invariables ; utiliser des listes de fréquence pour les mots les plus courants', page: 24 },
  { id: 'c3.fr.langue.regularites-orthographiques', cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ORTHO_LEX, competence: 'Mémoriser le lexique appris en s’appuyant sur ses régularités, sa formation et son étymologie', page: 24 },
  { id: 'c3.fr.culture.entrees', cycle: 3, discipline: 'french', domaine: 'c3-fr-culture', attendu: 'Lire des œuvres de littérature de jeunesse et du patrimoine, en classe et en lecture autonome', competence: 'Culture littéraire et artistique : le monstre, les récits d’aventures, les récits de création, résister au plus fort', page: 25 },
  // ---------- Mathématiques ----------
  { id: 'c3.ma.nombres.grands-entiers', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N1, competence: 'Connaître les unités de numération jusqu’aux milliards ; composer, décomposer, comparer, encadrer et placer les grands nombres entiers', page: 92 },
  { id: 'c3.ma.nombres.fractions-designations', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N1, competence: 'Connaître diverses désignations des fractions ; utiliser une fraction comme opérateur de partage ; placer une fraction sur une demi-droite graduée', page: 92 },
  { id: 'c3.ma.nombres.fractions-comparer', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N1, competence: 'Encadrer une fraction par deux entiers, comparer des fractions de même dénominateur, écrire une fraction comme somme d’un entier et d’une fraction, connaître des égalités usuelles', page: 92 },
  { id: 'c3.ma.nombres.decimaux-ecritures', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N1, competence: 'Connaître les unités de numération décimale (dixièmes, centièmes, millièmes), la valeur des chiffres, les écritures fractionnaire, à virgule et décomposées d’un décimal', page: 92 },
  { id: 'c3.ma.nombres.decimaux-comparer', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N1, competence: 'Placer un décimal sur une demi-droite graduée ; comparer, ranger, encadrer, intercaler des décimaux', page: 92 },
  { id: 'c3.ma.nombres.faits-numeriques', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N2, competence: 'Mobiliser les faits numériques mémorisés : tables de multiplication, multiples de 25 et de 50, diviseurs de 100', page: 93 },
  { id: 'c3.ma.nombres.calcul-mental', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N2, competence: 'Calcul mental et en ligne : multiplier ou diviser par 10, 100, 1000 ; complément à l’entier supérieur ; multiplier par 5, 25, 50, 0,1, 0,5 ; propriétés des opérations ; ordre de grandeur', page: 93 },
  { id: 'c3.ma.nombres.divisibilite', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N2, competence: 'Connaître les critères de divisibilité par 2, 3, 5, 9 et 10', page: 93 },
  { id: 'c3.ma.nombres.calcul-pose', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N2, competence: 'Calcul posé : addition, soustraction et multiplication d’entiers ou de décimaux ; division euclidienne ; division d’un décimal par un entier', page: 93 },
  { id: 'c3.ma.nombres.problemes', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N3, competence: 'Résoudre des problèmes mettant en jeu les quatre opérations, à une ou plusieurs étapes', page: 93 },
  { id: 'c3.ma.nombres.donnees', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N3, competence: 'Lire ou construire des tableaux (à double entrée), des diagrammes en bâtons ou circulaires, des graphiques cartésiens', page: 93 },
  { id: 'c3.ma.nombres.proportionnalite', cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_N3, competence: 'Reconnaître et résoudre des problèmes de proportionnalité (linéarité, passage à l’unité, coefficient) ; appliquer un pourcentage', page: 94 },
  { id: 'c3.ma.grandeurs.perimetre', cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_G1, competence: 'Calculer le périmètre d’un polygone, d’un carré, d’un rectangle ; la longueur d’un cercle', page: 94 },
  { id: 'c3.ma.grandeurs.aire', cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_G1, competence: 'Différencier périmètre et aire ; déterminer une aire par pavage ou par formule (carré, rectangle, triangle, disque) ; unités d’aire', page: 95 },
  { id: 'c3.ma.grandeurs.volume', cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_G1, competence: 'Relier volume et contenance ; volume du cube et du pavé droit ; unités de volume et de contenance', page: 95 },
  { id: 'c3.ma.grandeurs.angles', cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_G1, competence: 'Comparer des angles ; estimer qu’un angle est droit, aigu ou obtus ; mesurer en degrés avec le rapporteur', page: 95 },
  { id: 'c3.ma.grandeurs.unites-conversions', cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_G2, competence: 'Connaître les unités de longueur, de masse et de contenance, leurs relations avec les unités de numération ; convertir', page: 94 },
  { id: 'c3.ma.grandeurs.durees', cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_G3, competence: 'Calculer une durée entre deux instants, un instant à partir d’une durée ; unités de durée ; horaires de transport ou de cinéma', page: 95 },
  { id: 'c3.ma.espace.reperage', cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_E1, competence: 'Se repérer et décrire des déplacements sur un plan ou une carte ; programmer les déplacements d’un personnage', page: 97 },
  { id: 'c3.ma.espace.figures-solides', cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_E2, competence: 'Reconnaître, nommer, décrire les triangles particuliers, les quadrilatères particuliers, le cercle et les solides usuels, avec leur vocabulaire', page: 97 },
  { id: 'c3.ma.espace.construction', cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_E2, competence: 'Reproduire et construire des figures et des solides ; rédiger un programme de construction', page: 97 },
  { id: 'c3.ma.espace.relations', cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_E3, competence: 'Perpendicularité, parallélisme, alignement, distance ; symétrie axiale et médiatrice', page: 97 },
  { id: 'c3.ma.espace.echelle', cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_E3, competence: 'Reproduire une figure à une échelle donnée : agrandissement, réduction', page: 98 },
  // ---------- Anglais (langues vivantes) ----------
  { id: 'c3.en.ecouter.consignes', cycle: 3, discipline: 'english', domaine: 'c3-en-ecouter', attendu: EN_ECOUTER, competence: 'Comprendre l’ensemble des consignes utilisées en classe et suivre les instructions données', page: 33 },
  { id: 'c3.en.ecouter.mots-familiers', cycle: 3, discipline: 'english', domaine: 'c3-en-ecouter', attendu: EN_ECOUTER, competence: 'Comprendre des mots familiers et des expressions courantes ; reconstruire le sens à partir d’indices sonores et visuels', page: 33 },
  { id: 'c3.en.ecouter.histoire', cycle: 3, discipline: 'english', domaine: 'c3-en-ecouter', attendu: EN_ECOUTER, competence: 'Suivre le fil d’une histoire simple ; identifier le sujet et l’information essentielle d’un message oral court', page: 33 },
  { id: 'c3.en.lire.mots-isoles', cycle: 3, discipline: 'english', domaine: 'c3-en-lire', attendu: EN_LIRE, competence: 'Reconnaître des mots isolés dans un énoncé ou un texte court ; s’appuyer sur les mots outils et les structures simples', page: 34 },
  { id: 'c3.en.lire.textes-courts', cycle: 3, discipline: 'english', domaine: 'c3-en-lire', attendu: EN_LIRE, competence: 'Comprendre des textes courts et simples (consignes, correspondance, recette, texte informatif, récit) accompagnés d’un visuel ; identifier le type de document', page: 34 },
  { id: 'c3.en.parler.reproduire-presenter', cycle: 3, discipline: 'english', domaine: 'c3-en-parler', attendu: EN_PARLER, competence: 'Reproduire un modèle oral, lire à haute voix un texte bref, se présenter, décrire son environnement, raconter une histoire courte avec des supports visuels', page: 35 },
  { id: 'c3.en.ecrire.dictee', cycle: 3, discipline: 'english', domaine: 'c3-en-ecrire', attendu: EN_ECRIRE, competence: 'Copier des mots isolés et des textes courts ; écrire sous la dictée des expressions connues', page: 36 },
  { id: 'c3.en.ecrire.phrases', cycle: 3, discipline: 'english', domaine: 'c3-en-ecrire', attendu: EN_ECRIRE, competence: 'Renseigner un questionnaire ; produire quelques phrases sur soi, les autres, des objets et des lieux ; rédiger un courrier court d’après un modèle', page: 36 },
  { id: 'c3.en.dialoguer.contact-social', cycle: 3, discipline: 'english', domaine: 'c3-en-dialoguer', attendu: EN_DIALOGUER, competence: 'Établir un contact social : saluer, se présenter, présenter quelqu’un, demander des nouvelles, formules de politesse', page: 37 },
  { id: 'c3.en.dialoguer.renseignements', cycle: 3, discipline: 'english', domaine: 'c3-en-dialoguer', attendu: EN_DIALOGUER, competence: 'Dialoguer pour échanger ou obtenir des renseignements (itinéraire, horaire, prix) et sur des sujets familiers (école, loisirs, maison)', page: 37 },
  { id: 'c3.en.dialoguer.reagir', cycle: 3, discipline: 'english', domaine: 'c3-en-dialoguer', attendu: EN_DIALOGUER, competence: 'Réagir à des propositions (remercier, féliciter, s’excuser, accepter, refuser) ; répondre à des questions simples et en poser', page: 37 },
  { id: 'c3.en.culture.vie-quotidienne', cycle: 3, discipline: 'english', domaine: 'c3-en-culture', attendu: EN_CULTURE, competence: 'Lexique de la personne et de la vie quotidienne : le corps, les vêtements, le portrait, l’habitat, l’environnement, les besoins quotidiens', page: 39 },
  { id: 'c3.en.culture.reperes', cycle: 3, discipline: 'english', domaine: 'c3-en-culture', attendu: EN_CULTURE, competence: 'Repères géographiques, historiques et culturels des pays dont on étudie la langue ; quelques figures et grandes pages d’histoire', page: 39 },
  { id: 'c3.en.culture.imaginaire', cycle: 3, discipline: 'english', domaine: 'c3-en-culture', attendu: EN_CULTURE, competence: 'L’imaginaire : littérature de jeunesse, contes et légendes, héros et personnages de fiction', page: 39 },
  { id: 'c3.en.langue.groupe-verbal', cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_GRAMMAIRE, competence: 'Le verbe et son accord avec le sujet ; l’expression du présent, du passé et du futur ; les auxiliaires', page: 39 },
  { id: 'c3.en.langue.groupe-nominal', cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_GRAMMAIRE, competence: 'Nom et pronom, genre et nombre, articles, possessifs, démonstratifs, quantifieurs, prépositions, place et accord de l’adjectif, génitif', page: 39 },
  { id: 'c3.en.langue.phrase', cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_GRAMMAIRE, competence: 'Types et formes de phrase (déclarative, interrogative, exclamative, impérative, négative) ; ordre des mots ; mots de liaison ; quelques subordonnants', page: 39 },
  { id: 'c3.en.langue.phonologie', cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_PHONO, competence: 'Percevoir et reproduire les phonèmes spécifiques, l’accent tonique, le rythme et les schémas intonatifs', page: 40 },
  { id: 'c3.en.langue.phonie-graphie', cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_PHONO, competence: 'Lien phonie-graphie : percevoir la relation entre graphèmes et phonèmes spécifiques à la langue ; l’alphabet', page: 40 },
  // ---------- Histoire et géographie (6e) ----------
  { id: 'c3.hg.temps.periodes', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-temps', attendu: HG_TEMPS, competence: 'Situer chronologiquement des grandes périodes historiques ; mémoriser les repères historiques liés au programme', page: 67 },
  { id: 'c3.hg.temps.ordonner', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-temps', attendu: HG_TEMPS, competence: 'Ordonner des faits les uns par rapport aux autres et les situer dans une époque ou une période donnée', page: 67 },
  { id: 'c3.hg.temps.frise', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-temps', attendu: HG_TEMPS, competence: 'Utiliser des documents donnant à voir une représentation du temps (dont les frises chronologiques), à différentes échelles, et le lexique relatif au découpage du temps', page: 67 },
  { id: 'c3.hg.espace.localiser', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-espace', attendu: HG_ESPACE, competence: 'Nommer et localiser les grands repères géographiques ; nommer et localiser un lieu dans un espace géographique ; mémoriser les repères géographiques liés au programme', page: 67 },
  { id: 'c3.hg.espace.situer', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-espace', attendu: HG_ESPACE, competence: 'Nommer, localiser et caractériser des espaces ; situer des lieux et des espaces les uns par rapport aux autres ; appréhender la notion d’échelle géographique', page: 67 },
  { id: 'c3.hg.demarches.document', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_DOC, competence: 'Comprendre le sens général d’un document ; identifier le document et savoir pourquoi il doit être identifié ; extraire des informations pertinentes pour répondre à une question', page: 68 },
  { id: 'c3.hg.demarches.point-de-vue', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_DOC, competence: 'Savoir que le document exprime un point de vue ; identifier et questionner son sens implicite', page: 68 },
  { id: 'c3.hg.demarches.lexique', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_LANGAGES, competence: 'S’approprier et utiliser un lexique historique et géographique approprié', page: 68 },
  { id: 'c3.hg.demarches.cartes', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_LANGAGES, competence: 'Utiliser des cartes analogiques et numériques à différentes échelles, des photographies de paysages ou de lieux ; réaliser ou compléter des productions graphiques', page: 68 },
  { id: 'c3.hg.demarches.ecrire-dire', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_LANGAGES, competence: 'Écrire pour structurer sa pensée et son savoir, pour argumenter et pour communiquer ; reconnaître un récit historique ; s’exprimer à l’oral pour penser, communiquer et échanger', page: 68 },
  { id: 'c3.hg.demarches.raisonner', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_RAISONNER, competence: 'Poser des questions, se poser des questions ; formuler des hypothèses ; vérifier ; justifier ; s’informer dans le monde du numérique ; coopérer et mutualiser', page: 67 },
  { id: 'c3.hg.histoire.debuts-humanite', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H1, competence: 'Les débuts de l’humanité : premiers humains, peuplement de la Terre, grandes migrations', page: 71 },
  { id: 'c3.hg.histoire.neolithique', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H1, competence: 'La « révolution » néolithique : agriculture, élevage, sédentarisation', page: 71 },
  { id: 'c3.hg.histoire.premiers-etats', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H1, competence: 'Premiers États, premières écritures', page: 71 },
  { id: 'c3.hg.histoire.cites-grecques', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H2, competence: 'Le monde des cités grecques : l’univers culturel commun des Grecs vivant dans des cités rivales ; la naissance de la démocratie à Athènes', page: 72 },
  { id: 'c3.hg.histoire.rome-mythe', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H2, competence: 'Rome du mythe à l’histoire : le mythe de sa fondation, qui permet à Rome d’asseoir sa domination', page: 72 },
  { id: 'c3.hg.histoire.monotheisme-juif', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H2, competence: 'La naissance du monothéisme juif dans un monde polythéiste', page: 72 },
  { id: 'c3.hg.histoire.empire-romain', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H3, competence: 'Conquêtes, paix romaine et romanisation', page: 72 },
  { id: 'c3.hg.histoire.chretiens', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H3, competence: 'Des chrétiens dans l’empire', page: 72 },
  { id: 'c3.hg.histoire.route-de-la-soie', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H3, competence: 'Les relations de l’empire romain avec les autres mondes anciens : l’ancienne route de la soie et la Chine des Han', page: 72 },
  { id: 'c3.hg.geographie.metropoles', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G1, competence: 'Les métropoles et leurs habitants', page: 75 },
  { id: 'c3.hg.geographie.ville-de-demain', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G1, competence: 'La ville de demain', page: 75 },
  { id: 'c3.hg.geographie.contraintes', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G2, competence: 'Habiter un espace à forte(s) contrainte(s) naturelle(s) ou/et de grande biodiversité', page: 76 },
  { id: 'c3.hg.geographie.agricole', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G2, competence: 'Habiter un espace de faible densité à vocation agricole', page: 76 },
  { id: 'c3.hg.geographie.littoral-portuaire', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G3, competence: 'Un littoral industrialo-portuaire', page: 76 },
  { id: 'c3.hg.geographie.littoral-touristique', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G3, competence: 'Un littoral touristique', page: 76 },
  { id: 'c3.hg.geographie.population-mondiale', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G4, competence: 'La répartition de la population mondiale et ses dynamiques', page: 76 },
  { id: 'c3.hg.geographie.occupation', cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G4, competence: 'La variété des formes d’occupation spatiale dans le monde', page: 76 },
  // ---------- SVT (sciences et technologie, 6e : programme du cycle 3 en vigueur à la rentrée 2023) ----------
  { id: 'c3.sv.demarches.observer', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_DEMARCHE, competence: 'Formuler une question ou une hypothèse ; proposer ou suivre un protocole ; utiliser des instruments d’observation ; interpréter des résultats et en tirer des conclusions', page: 80 },
  { id: 'c3.sv.demarches.langages', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_LANGAGES, competence: 'Exploiter un document constitué de divers supports (texte, schéma, graphique, tableau, carte heuristique) ; passer d’une représentation à une autre ; rendre compte avec un vocabulaire précis', page: 80 },
  { id: 'c3.sv.demarches.responsable', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_RESPONSABLE, competence: 'Relier des connaissances acquises en sciences et technologie à des questions de santé, de sécurité et d’environnement ; comprendre et expliquer des décisions collectives et responsables', page: 81 },
  { id: 'c3.sv.demarches.situer', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_SITUER, competence: 'Maîtriser les notions d’échelle spatiale et temporelle et en citer quelques ordres de grandeur ; identifier comment se construit un savoir scientifique dans son contexte', page: 81 },
  { id: 'c3.sv.demarches.esprit-critique', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_CRITIQUE, competence: 'Identifier des sources d’informations fiables ; vérifier l’existence de preuves ; évaluer la pertinence des arguments ; distinguer une croyance d’un savoir scientifique', page: 81 },
  { id: 'c3.sv.vivant.cellule', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_PANORAMA, competence: 'Les niveaux d’organisation d’un être vivant (organisme, appareil, organe) ; observer des cellules au microscope ; la cellule, unité structurale commune à tous les êtres vivants', page: 88 },
  { id: 'c3.sv.vivant.classer', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_PANORAMA, competence: 'Classer en groupes emboîtés et établir des parentés à partir des attributs ; lire des arbres de parenté simples ; les différents types de classification et leurs objectifs', page: 88 },
  { id: 'c3.sv.vivant.evolution', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_PANORAMA, competence: 'La biodiversité actuelle et passée : la diversité au sein d’une espèce, les clés de détermination, les fossiles et les paléoenvironnements, les grandes crises biologiques sur une échelle des temps', page: 88 },
  { id: 'c3.sv.vivant.alimentation', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_ALIMENTS, competence: 'Les besoins alimentaires et des comportements favorables à la santé ; la diversité des aliments selon les cultures ; conserver les aliments pour limiter les risques sanitaires ; les microorganismes et la fermentation', page: 89 },
  { id: 'c3.sv.vivant.developpement', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_CYCLE, competence: 'Les étapes d’un cycle de vie ; la pollinisation, de la fleur au fruit ; la puberté ; les organes reproducteurs, la fécondation et le développement de l’être humain', page: 90 },
  { id: 'c3.sv.terre.systeme-solaire', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_TERRE, competence: 'Situer la Terre dans le système solaire ; les conditions qui permettent la vie sur Terre : atmosphère et température compatibles avec la vie, présence d’eau liquide', page: 96 },
  { id: 'c3.sv.terre.phenomenes', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_TERRE, competence: 'Les indices de l’activité interne ou externe de la Terre (séismes, volcans, vents, courants océaniques) ; distinguer la météorologie du climat ; un risque naturel et sa prévention ; des ressources liées à l’activité de la Terre', page: 96 },
  { id: 'c3.sv.terre.climat', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_TERRE, competence: 'Le réchauffement climatique récent : argumenter à partir de données, le relier aux gaz à effet de serre émis par les activités humaines ; ses conséquences sur le peuplement des milieux ; atténuation et adaptation', page: 96 },
  { id: 'c3.sv.terre.peuplement', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_ECOSYSTEME, competence: 'Un écosystème : milieu de vie, êtres vivants et relations entre espèces ; relier le peuplement d’un milieu à ses conditions et aux saisons ; les adaptations à la mauvaise saison ; les effets d’une perturbation', page: 97 },
  { id: 'c3.sv.terre.chaines-alimentaires', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_ECOSYSTEME, competence: 'Les besoins des végétaux (lumière, eau, sels minéraux, dioxyde de carbone) et leur place à la base des chaînes alimentaires ; les réseaux alimentaires ; la décomposition de la matière organique par les êtres vivants du sol', page: 97 },
  { id: 'c3.sv.terre.environnement', cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_ECOSYSTEME, competence: 'Les répercussions positives et négatives des actions humaines sur l’environnement ; une exploitation raisonnée des ressources ; des actions et des objets qui favorisent la biodiversité', page: 98 },
  // ---------- Physique-chimie (sciences et technologie, 6e : programme du cycle 3 en vigueur à la rentrée 2023) ----------
  { id: 'c3.pc.demarches.experimenter', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-demarches', attendu: ST_DEMARCHE, competence: 'Formuler une question ou une hypothèse ; concevoir et mettre en œuvre une expérience pour la tester ; interpréter les résultats et en tirer des conclusions', page: 80 },
  { id: 'c3.pc.demarches.mesurer', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-demarches', attendu: ST_DEMARCHE, competence: 'Utiliser des instruments d’observation et de mesure ; étudier les phénomènes en mobilisant des grandeurs physiques', page: 80 },
  { id: 'c3.pc.demarches.langages', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-demarches', attendu: ST_LANGAGES, competence: 'Exploiter un document constitué de divers supports (texte, schéma, graphique, tableau) ; utiliser différents modes de représentation et passer de l’un à l’autre ; rendre compte avec un vocabulaire précis', page: 80 },
  { id: 'c3.pc.matiere.etats', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATIERE, competence: 'Les états solide, liquide et gazeux ; les changements d’état et leur réversibilité ; les températures de changement d’état et les paliers de température', page: 82 },
  { id: 'c3.pc.matiere.grandeurs', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATIERE, competence: 'Masse et volume : les mesurer (balance, déplacement de liquide), convertir leurs unités ; la proportionnalité entre la masse et le volume d’un corps homogène', page: 82 },
  { id: 'c3.pc.matiere.materiaux', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATERIAUX, competence: 'Comparer et trier des matériaux selon leurs propriétés physiques (conductivité thermique ou électrique, capacité à interagir avec un aimant) ; leur durée de décomposition dans la nature', page: 82 },
  { id: 'c3.pc.matiere.melanges', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATIERE, competence: 'Séparer les constituants d’un mélange (tamisage, décantation, filtration, évaporation) ; la dissolution et la saturation ; la masse totale se conserve ; les liquides non miscibles', page: 83 },
  { id: 'c3.pc.matiere.transformations', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATIERE, competence: 'Un mélange qui produit une transformation chimique (changement de couleur, gaz) ; la sécurité des produits ménagers et les pictogrammes de danger ; la composition de l’air et les gaz à effet de serre', page: 83 },
  { id: 'c3.pc.matiere.mouvements', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MOUVEMENT, competence: 'Mouvement rectiligne ou circulaire, par rapport à un observateur ; vitesse constante ou variable ; calculer la vitesse d’un mouvement uniforme ; l’année et la révolution de la Terre, le jour et sa rotation', page: 84 },
  { id: 'c3.pc.matiere.energie', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_ENERGIE, competence: 'Les formes d’énergie (de pesanteur, cinétique, chimique, thermique, électrique, nucléaire, lumineuse) ; une chaîne énergétique ; les ressources renouvelables ou non, et les conséquences de leur utilisation sur l’environnement', page: 85 },
  { id: 'c3.pc.matiere.lumiere', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_OMBRES, competence: 'Interpréter l’alternance du jour et de la nuit à l’aide d’un modèle ; associer les saisons à l’inclinaison du Soleil et à la durée du jour pour un observateur sur la Terre', page: 86 },
  { id: 'c3.pc.matiere.circuit', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_CIRCUIT, competence: 'Le circuit électrique à une boucle, avec un convertisseur d’énergie ou un capteur ; sa représentation schématique normalisée ; la conductivité électrique des matériaux ; les règles de sécurité électrique', page: 86 },
  { id: 'c3.pc.matiere.signal', cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_SIGNAL, competence: 'Identifier différents signaux pour transmettre de l’information (signal sonore, lumineux, électrique) ; citer quelques applications', page: 87 },
  // ---------- Technologie (sciences et technologie, 6e : programme du cycle 3 en vigueur à la rentrée 2023) ----------
  // En 6e, la partie « Les objets techniques au cœur de la société » ne fixe que des attendus de fin de cours moyen,
  // repris en sixième par leurs liens avec les autres thèmes (pages 91 à 95) : les compétences les résument ensemble.
  { id: 'c3.te.demarches.concevoir', cycle: 3, discipline: 'technology', domaine: 'c3-te-demarches', attendu: ST_CONCEVOIR, competence: 'Imaginer un objet technique en réponse à un besoin ; concevoir et réaliser une maquette pour modéliser un phénomène naturel ou un objet technique', page: 80 },
  { id: 'c3.te.demarches.representer', cycle: 3, discipline: 'technology', domaine: 'c3-te-demarches', attendu: ST_LANGAGES, competence: 'Utiliser différents modes de représentation (schéma, dessin, croquis, tableau, texte) et passer de l’un à l’autre ; rendre compte avec un vocabulaire précis', page: 80 },
  { id: 'c3.te.demarches.numerique', cycle: 3, discipline: 'technology', domaine: 'c3-te-demarches', attendu: ST_NUMERIQUE, competence: 'Utiliser des outils numériques pour communiquer des résultats, faire des recherches, traiter des données, simuler des phénomènes', page: 80 },
  { id: 'c3.te.objets.evolution', cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_BESOIN, competence: 'Les besoins (se déplacer, se chauffer, s’alimenter) et leur évolution ; les évolutions d’un objet selon le contexte (historique, géographique, économique, culturel, technologique) ; les détournements d’usage', page: 91 },
  { id: 'c3.te.objets.fonction', cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_FONCTIONNEMENT, competence: 'Distinguer un objet technique d’un objet naturel ; distinguer le besoin et les fonctions techniques d’un objet ; associer les solutions technologiques aux fonctions techniques', page: 91 },
  { id: 'c3.te.objets.fonctionnement', cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_FONCTIONNEMENT, competence: 'Identifier les sous-ensembles d’un objet et décrire son fonctionnement par un schéma ; les mouvements de ses parties (poulies, engrenages) et les conversions d’énergie qu’il réalise', page: 92 },
  { id: 'c3.te.objets.materiaux', cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_FONCTIONNEMENT, competence: 'Identifier les matériaux d’un objet ; choisir un matériau selon ses propriétés physiques (thermiques, électriques), en lien avec les propriétés de la matière', page: 92 },
  { id: 'c3.te.objets.probleme', cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_CONCEPTION, competence: 'Rechercher des idées de solutions à un problème technique par des croquis ou des schémas ; comparer des solutions par une analyse critique ; prendre en compte une contrainte (imperméabilité, poids, autonomie)', page: 93 },
  { id: 'c3.te.objets.recyclage', cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_CONCEPTION, competence: 'Les étapes du cycle de vie d’un objet technique ; des choix raisonnés selon leurs conséquences sur l’environnement, en lien avec la décomposition des matériaux', page: 94 },
  { id: 'c3.te.objets.realiser', cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_CONCEPTION, competence: 'Organiser et planifier en équipe la réalisation d’une maquette ; réaliser des maquettes simples pour matérialiser une solution ; vérifier qu’elle répond au problème posé', page: 94 },
  { id: 'c3.te.objets.information', cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_PROGRAMMATION, competence: 'Les objets reliés entre eux par des réseaux (objets communicants, transmission et traitement de données) ; la chaîne d’information et d’action d’un objet programmable, ses capteurs et ses actionneurs', page: 94 },
  { id: 'c3.te.objets.programmer', cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_PROGRAMMATION, competence: 'Coder un algorithme simple qui agit sur un objet technique (programmation par blocs) ; comprendre un programme simple et le traduire en langage naturel ; critiquer un programme', page: 95 },
] as const satisfies readonly ProgrammeEntry[];
