// Cycle 3 (CM1, CM2, 6e), résumé au grain d'une mission, pour la seule classe de 6e : le français et les maths sur les
// programmes en vigueur à la rentrée 2025, l'anglais sur le programme des langues vivantes du collège (2025), l'histoire
// et la géographie sur l'annexe de 2020, les sciences et la technologie sur le programme de 2023 (sources.ts).
// Les libellés sont des résumés fidèles du texte officiel ; le texte fait foi (page du PDF indiquée).
import type { ProgrammeDomaine, ProgrammeEntry } from './types';

export const DOMAINES_C3: readonly ProgrammeDomaine[] = [
  // Français, mathématiques et anglais : les textes en vigueur en 6e depuis la rentrée 2025 (sources.ts), lus le
  // 7 octobre 2026. Ils sont rangés par classe (CM1, CM2, 6e) : les pages sont celles de la partie de 6e, sauf quand la
  // compétence n'y est que consolidée (le libellé dit alors d'où elle vient).
  { id: 'c3-fr-lecture', cycle: 3, discipline: 'french', title: 'Lecture', page: 2, source: 'c3-fr-2025' },
  { id: 'c3-fr-culture', cycle: 3, discipline: 'french', title: 'Culture littéraire et artistique', page: 6, source: 'c3-fr-2025' },
  { id: 'c3-fr-ecriture', cycle: 3, discipline: 'french', title: 'Écriture', page: 8, source: 'c3-fr-2025' },
  { id: 'c3-fr-oral', cycle: 3, discipline: 'french', title: 'Oral', page: 10, source: 'c3-fr-2025' },
  { id: 'c3-fr-langue', cycle: 3, discipline: 'french', title: 'Vocabulaire ; grammaire et orthographe grammaticale', page: 13, source: 'c3-fr-2025' },
  { id: 'c3-ma-nombres', cycle: 3, discipline: 'maths', title: 'Nombres, calcul et résolution de problèmes', page: 5, source: 'c3-ma-2025' },
  { id: 'c3-ma-grandeurs', cycle: 3, discipline: 'maths', title: 'Grandeurs et mesures', page: 16, source: 'c3-ma-2025' },
  { id: 'c3-ma-espace', cycle: 3, discipline: 'maths', title: 'Espace et géométrie', page: 20, source: 'c3-ma-2025' },
  { id: 'c3-ma-donnees', cycle: 3, discipline: 'maths', title: 'Organisation et gestion de données et probabilités', page: 24, source: 'c3-ma-2025' },
  { id: 'c3-ma-proportionnalite', cycle: 3, discipline: 'maths', title: 'La proportionnalité', page: 26, source: 'c3-ma-2025' },
  { id: 'c3-ma-informatique', cycle: 3, discipline: 'maths', title: 'Initiation à la pensée informatique', page: 27, source: 'c3-ma-2025' },
  // L'anglais de 6e : le programme d'anglais des classes de collège, partie « Classe de sixième » (pages 5 à 13). Les
  // domaines gardent le découpage par activité langagière ; le texte réunit compréhension de l'oral et de l'écrit, et
  // expression orale et écrite.
  { id: 'c3-en-culture', cycle: 3, discipline: 'english', title: 'Langues vivantes : repères culturels', page: 6, source: 'lv-en-2025' },
  { id: 'c3-en-ecouter', cycle: 3, discipline: 'english', title: 'Langues vivantes : compréhension de l’oral', page: 7, source: 'lv-en-2025' },
  { id: 'c3-en-lire', cycle: 3, discipline: 'english', title: 'Langues vivantes : compréhension de l’écrit', page: 7, source: 'lv-en-2025' },
  { id: 'c3-en-parler', cycle: 3, discipline: 'english', title: 'Langues vivantes : expression orale', page: 7, source: 'lv-en-2025' },
  { id: 'c3-en-ecrire', cycle: 3, discipline: 'english', title: 'Langues vivantes : expression écrite', page: 7, source: 'lv-en-2025' },
  { id: 'c3-en-dialoguer', cycle: 3, discipline: 'english', title: 'Langues vivantes : interaction orale et écrite, médiation', page: 9, source: 'lv-en-2025' },
  { id: 'c3-en-langue', cycle: 3, discipline: 'english', title: 'Langues vivantes : outils linguistiques', page: 10, source: 'lv-en-2025' },
  // Histoire et géographie : pages et libellés vérifiés dans le PDF cité par sources.ts (7 octobre 2026). Seule la
  // classe de 6e est résumée : le CM1 et le CM2 ne sont pas dans l'application.
  { id: 'c3-hg-temps', cycle: 3, discipline: 'history-geography', title: 'Histoire et géographie : se repérer dans le temps', page: 67 },
  { id: 'c3-hg-espace', cycle: 3, discipline: 'history-geography', title: 'Histoire et géographie : se repérer dans l’espace', page: 67 },
  { id: 'c3-hg-demarches', cycle: 3, discipline: 'history-geography', title: 'Histoire et géographie : raisonner, comprendre un document, pratiquer différents langages', page: 67 },
  { id: 'c3-hg-histoire', cycle: 3, discipline: 'history-geography', title: 'Histoire, classe de sixième', page: 71 },
  { id: 'c3-hg-geographie', cycle: 3, discipline: 'history-geography', title: 'Géographie, classe de sixième', page: 75 },
  // Sciences et technologie, découpées en trois disciplines comme au collège (choix C du mainteneur, 5 octobre 2026) :
  // SVT (le vivant, la Terre peuplée par des êtres vivants), physique-chimie (matière, mouvement, énergie,
  // information), technologie (les objets techniques au cœur de la société). Le texte en vigueur en 6e est celui du
  // BO n° 25 du 22 juin 2023, qui a remplacé cette partie du PDF de 2020 : libellés et pages sont lus dans le
  // programme du cycle 3 en vigueur à la rentrée 2023 (source c3-2023, 7 octobre 2026). Les compétences travaillées
  // sont communes aux trois disciplines (page 80) : chaque discipline reprend celles qu'elle travaille.
  { id: 'c3-sv-demarches', cycle: 3, discipline: 'life-earth-sciences', title: 'Sciences et technologie : compétences travaillées (SVT)', page: 80, source: 'c3-2023' },
  { id: 'c3-sv-vivant', cycle: 3, discipline: 'life-earth-sciences', title: 'Le vivant, sa diversité et les fonctions qui le caractérisent', page: 87, source: 'c3-2023' },
  { id: 'c3-sv-terre', cycle: 3, discipline: 'life-earth-sciences', title: 'La Terre, une planète peuplée par des êtres vivants', page: 95, source: 'c3-2023' },
  { id: 'c3-pc-demarches', cycle: 3, discipline: 'physics-chemistry', title: 'Sciences et technologie : compétences travaillées (physique-chimie)', page: 80, source: 'c3-2023' },
  { id: 'c3-pc-matiere', cycle: 3, discipline: 'physics-chemistry', title: 'Matière, mouvement, énergie, information', page: 81, source: 'c3-2023' },
  { id: 'c3-te-demarches', cycle: 3, discipline: 'technology', title: 'Sciences et technologie : compétences travaillées (technologie)', page: 80, source: 'c3-2023' },
  { id: 'c3-te-objets', cycle: 3, discipline: 'technology', title: 'Les objets techniques au cœur de la société', page: 91, source: 'c3-2023' },
];

// La source et les classes de chaque compétence (types.ts) : en 6e, chaque texte ne vaut que pour la 6e.
const FR = { source: 'c3-fr-2025', classes: ['6e'] } as const;
const MA = { source: 'c3-ma-2025', classes: ['6e'] } as const;
const EN = { source: 'lv-en-2025', classes: ['6e'] } as const;
const HG = { source: 'c3', classes: ['6e'] } as const;
const ST = { source: 'c3-2023', classes: ['6e'] } as const;

// Les textes de 2025 n'ont pas d'attendus de fin de cycle : chaque compétence du texte (un titre, puis ses objectifs
// d'apprentissage pour chaque classe) tient lieu d'attendu ; le libellé résume les objectifs de 6e.
const FR_FLUIDITE = 'Lire avec fluidité';
const FR_VOIX = 'Lire à voix haute avec expressivité';
const FR_SEUL = 'Lire et comprendre seul des textes, des documents et des images';
const FR_DOCS = 'Lire et comprendre des textes, des documents et des images pour apprendre dans toutes les disciplines';
const FR_ENRICHIR = 'Enrichir son vocabulaire dans toutes les disciplines';
const FR_RELATIONS = 'Établir des relations entre les mots';
const FR_MEMORISER = 'Mémoriser l’orthographe des mots';
const FR_CONSTITUANTS = 'Identifier les constituants d’une phrase simple';
const FR_COMPLEXE = 'Se repérer dans la phrase complexe';
const FR_ORTHO_GRAM = 'Acquérir l’orthographe grammaticale';
const FR_CONJUGAISON = 'Approfondir sa maîtrise de la conjugaison';
const MA_ENTIERS_DECIMAUX = 'Les nombres entiers et décimaux';
const MA_FRACTIONS = 'Les fractions';
const MA_ALGEBRE = 'Algèbre : résoudre des problèmes mettant en jeu des nombres inconnus';
const MA_LONGUEURS = 'Les longueurs';
const MA_AIRES = 'Les aires';
const MA_VOLUMES = 'Les volumes';
const MA_DUREES = 'Le repérage dans le temps et les durées';
const MA_CONFIGURATIONS = 'Étude de configurations planes';
const MA_VISION = 'La vision dans l’espace';
const MA_DONNEES = 'Organisation et gestion de données';
const MA_PROBABILITES = 'Les probabilités';
const MA_PROPORTIONNALITE = 'La proportionnalité';
const MA_INFORMATIQUE = 'Initiation à la pensée informatique';
// Anglais : ce que sait faire l'élève en fin de 6e (A1, A1+ pour la langue apprise dès le primaire), activité par activité.
const EN_COMPRENDRE = 'Compréhension de l’oral et de l’écrit (A1, A1+)';
const EN_EXPRIMER = 'Expression orale et écrite (A1, A1+)';
const EN_INTERAGIR = 'Interaction orale et écrite, médiation (A1, A1+)';
const EN_AXES = 'Repères culturels : les cinq axes, tous traités dans l’année';
const EN_OUTILS = 'Outils linguistiques (A1, A1+)';

const HG_TEMPS = 'Se repérer dans le temps : construire des repères historiques';
const HG_ESPACE = 'Se repérer dans l’espace : construire des repères géographiques';
const HG_DOC = 'Comprendre un document';
const HG_LANGAGES = 'Pratiquer différents langages en histoire et en géographie';
const HG_RAISONNER = 'Raisonner, justifier une démarche et les choix effectués';
const HG_H1 = 'Thème 1 : la longue histoire de l’humanité et des migrations';
const HG_H2 = 'Thème 2 : récits fondateurs, croyances et citoyenneté dans la Méditerranée antique au Ier millénaire avant J.-C.';
const HG_H3 = 'Thème 3 : l’empire romain dans le monde antique';
const HG_G1 = 'Thème 1 : habiter une métropole';
const HG_G2 = 'Thème 2 : habiter un espace de faible densité';
const HG_G3 = 'Thème 3 : habiter les littoraux';
const HG_G4 = 'Thème 4 : le monde habité';

// Sciences et technologie (programme du cycle 3 en vigueur à la rentrée 2023) : les compétences travaillées (page 80),
// puis les attendus de fin de cycle de chaque partie, réunis quand une compétence en couvre plusieurs.
const ST_DEMARCHE = 'Pratiquer des démarches scientifiques et technologiques';
const ST_CONCEVOIR = 'Concevoir, créer, réaliser';
const ST_LANGAGES = 'Pratiquer des langages';
const ST_NUMERIQUE = 'Mobiliser des outils numériques';
const ST_RESPONSABLE = 'Adopter un comportement éthique et responsable';
const ST_SITUER = 'Se situer dans l’espace et dans le temps';
const ST_CRITIQUE = 'Faire preuve d’esprit critique';
const PC_MATIERE = 'Décrire un échantillon de matière à l’aide du vocabulaire scientifique et des grandeurs physiques : masse, volume ; caractériser la diversité de la matière et de ses transformations à l’échelle macroscopique';
const PC_MATERIAUX = 'Utiliser les propriétés physiques des matériaux pour les classer, notamment à des fins de tri';
const PC_MOUVEMENT = 'Décrire un mouvement en précisant le point de vue ; caractériser un mouvement par des mesures';
const PC_ENERGIE = 'Identifier les formes d’énergie mises en jeu dans un dispositif de conversion d’énergie ; rechercher et exploiter des informations sur les ressources en énergie et leur utilisation, en exerçant son esprit critique';
const PC_OMBRES = 'Interpréter la formation d’ombres, en particulier dans le contexte du système Soleil-Terre-Lune';
const PC_CIRCUIT = 'Mettre en œuvre des circuits électriques à une boucle en respectant des consignes de sécurité';
const PC_SIGNAL = 'Identifier des signaux de natures différentes et citer des applications dans lesquelles un signal permet de transmettre une information';
const SV_PANORAMA = 'Caractériser la richesse, l’unité et la diversité actuelle et passée du vivant ; classer les organismes et établir les liens de parenté';
const SV_ALIMENTS = 'Expliquer le rôle des aliments pour le fonctionnement de l’organisme ; identifier les principes des technologies mises en œuvre pour transformer et conserver les aliments';
const SV_CYCLE = 'Décrire le cycle de vie d’une plante à fleurs et celui d’un animal ; décrire les changements pubertaires associés à la capacité de se reproduire ; distinguer la dimension biologique de la sexualité humaine de ses autres dimensions';
const SV_TERRE = 'Identifier l’activité de la planète Terre et ses conséquences ; décrire les conditions de la vie terrestre ; différencier la météorologie du climat ; construire une argumentation scientifique pour expliquer le réchauffement climatique actuel';
const SV_ECOSYSTEME = 'Décrire un écosystème et caractériser ses interactions ; mettre en évidence la place et l’interdépendance des êtres vivants dans un réseau trophique ; caractériser les conséquences d’une action humaine sur un écosystème';
const TE_BESOIN = 'Identifier un besoin exprimé par la société et lui associer des objets techniques ; distinguer un objet technique d’un objet naturel ; repérer les évolutions des objets techniques selon leur contexte d’utilisation ; citer des objets détournés de leur usage initial';
const TE_FONCTIONNEMENT = 'Distinguer besoins, fonctions techniques et solutions technologiques ; décrire un objet technique par un schéma (son fonctionnement) et un croquis (ce que l’on observe)';
const TE_CONCEPTION = 'Décrire et pratiquer la démarche technologique dans le cadre d’un projet ; participer à un travail collectif ; identifier les liens entre des choix de conception et leurs effets sur les étapes du cycle de vie d’un objet technique';
const TE_PROGRAMMATION = 'Repérer la chaîne d’information et la chaîne d’action d’un objet programmable ; programmer un objet technique pour obtenir un comportement attendu';

export const ENTRIES_C3 = [
  // ---------- Français (programme de 2025, partie de 6e) ----------
  { id: 'c3.fr.lecture.fluidite', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_FLUIDITE, competence: 'Lire silencieusement et à voix haute en prenant en compte les groupes syntaxiques, la ponctuation et les liaisons ; viser 130 mots par minute en moyenne', page: 5 },
  { id: 'c3.fr.lecture.voix-haute', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_VOIX, competence: 'Lire à voix haute, avec aisance et expressivité, un texte de 10 à 20 lignes en regardant l’auditoire ; rendre les émotions des personnages', page: 5 },
  { id: 'c3.fr.lecture.explicite', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_SEUL, competence: 'Dégager le sens global d’un texte ; repérer les informations explicites, une information plus ou moins saillante', page: 5 },
  { id: 'c3.fr.lecture.implicite', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_SEUL, competence: 'Repérer les informations implicites et les liens logiques, effectuer des inférences ; justifier ses réponses en prenant appui sur le texte', page: 5 },
  { id: 'c3.fr.lecture.reprises', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_SEUL, competence: 'Repérer les reprises nominales ; mettre en relation un pronom personnel avec son antécédent (grammaire, p. 20)', page: 5 },
  { id: 'c3.fr.lecture.genres', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_SEUL, competence: 'Dégager les principales caractéristiques d’un texte et le rattacher à un genre', page: 5 },
  { id: 'c3.fr.lecture.documents', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_DOCS, competence: 'Identifier la nature et la source des documents ; mettre en relation les informations d’un document composite ; comparer des documents de genres différents', page: 5 },
  { id: 'c3.fr.lecture.lexique-contexte', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-lecture', attendu: FR_ENRICHIR, competence: 'Choisir de manière autonome la stratégie pour comprendre un mot inconnu : en déduire, en vérifier ou en rechercher le sens (vocabulaire)', page: 15 },
  { id: 'c3.fr.culture.entrees', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-culture', attendu: 'Culture littéraire et artistique, sixième : cinq entrées, chacune liée à un genre', competence: 'Récits des origines, poésie, ruses au théâtre, aventure, monstres ; lire au moins six œuvres complètes dans l’année (p. 6)', page: 7 },
  { id: 'c3.fr.ecriture.copier', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-ecriture', attendu: 'Écrire à la main de manière fluide et efficace', competence: 'Copier des textes de façon lisible, régulière, soignée et sans erreur d’orthographe ou de ponctuation', page: 10 },
  { id: 'c3.fr.ecriture.rediger', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-ecriture', attendu: 'Produire des écrits variés ; écrire pour réfléchir, apprendre et mémoriser', competence: 'Résumer, synthétiser, écrire des textes personnels (avis justifié, récit) ; utiliser le brouillon et réviser son texte', page: 10 },
  { id: 'c3.fr.oral.comprendre-s-exprimer', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-oral', attendu: 'Écouter pour comprendre ; dire pour être compris dans toutes les disciplines ; participer à des échanges verbaux', competence: 'Comprendre un message oral et en reformuler les informations ; présenter, expliquer, argumenter ; prendre la parole en respectant les codes de la communication', page: 12 },
  // Le texte de 6e ne nomme plus les correspondances entre graphèmes et phonèmes : le cycle 3 « vise toujours
  // l’automatisation du déchiffrage » (principes, p. 2), et le CM1 lit « sans confondre les graphèmes, même complexes »
  // (p. 4). Les îles de 6e les travaillent en remédiation, pour les élèves dys.
  { id: 'c3.fr.langue.phonemes-graphemes', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: 'Principes : au cycle 3, la lecture vise toujours l’automatisation du déchiffrage', competence: 'Lire sans confondre les graphèmes, même complexes (objectif du CM1, p. 4) : en 6e, en remédiation', page: 2 },
  { id: 'c3.fr.langue.derivation-composition', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_RELATIONS, competence: 'Composer et décomposer des mots pour les analyser et en créer de nouveaux ; différencier les mots simples, dérivés et composés', page: 15 },
  { id: 'c3.fr.langue.racines', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_RELATIONS, competence: 'Se sensibiliser à l’étymologie et à l’évolution du sens des mots', page: 15 },
  { id: 'c3.fr.langue.familles-champ-lexical', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_RELATIONS, competence: 'S’appuyer sur les relations morphologiques et sémantiques entre les mots (familles de mots) ; les organiser en réseau dans un outil de vocabulaire (p. 13)', page: 15 },
  { id: 'c3.fr.langue.synonymie', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_RELATIONS, competence: 'Donner des synonymes et des antonymes qui respectent la classe grammaticale du mot ; utiliser à bon escient les mots polysémiques', page: 15 },
  { id: 'c3.fr.langue.mots-frequents', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_MEMORISER, competence: 'Écrire correctement les mots fréquents en situation autonome (au cours moyen : en s’appuyant sur les régularités et la formation, p. 15)', page: 15 },
  { id: 'c3.fr.langue.genre-nombre', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ORTHO_GRAM, competence: 'Variations en genre et en nombre des noms, adjectifs et déterminants ; pluriels irréguliers (-x, -al/-aux) et marques du féminin stabilisés en fin de cycle', page: 16 },
  { id: 'c3.fr.langue.reconnaitre-verbe', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONJUGAISON, competence: 'Identifier le verbe dans la phrase, le distinguer du nom ; repérer le radical et la terminaison (marques de temps et de personne)', page: 16 },
  { id: 'c3.fr.langue.types-formes', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONSTITUANTS, competence: 'Types de phrases (déclaratives, interrogatives, impératives) et formes négative et exclamative : terminologie du cycle, étudiés au CM1 (p. 17)', page: 16 },
  { id: 'c3.fr.langue.nature-fonction', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONSTITUANTS, competence: 'Identifier les mots et les groupes de mots selon leur nature ; identifier le groupe nominal quelle que soit sa fonction ; distinguer nature et fonction', page: 20 },
  { id: 'c3.fr.langue.sujet', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONSTITUANTS, competence: 'Identifier le groupe sujet parmi tous les constituants de la phrase simple, y compris inversé (CM2, p. 19)', page: 20 },
  { id: 'c3.fr.langue.complements', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONSTITUANTS, competence: 'Identifier COD, COI et compléments circonstanciels (de temps, de lieu, de cause) par les manipulations syntaxiques et la construction du verbe', page: 20 },
  { id: 'c3.fr.langue.attribut-gn', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONSTITUANTS, competence: 'Opposer attribut du sujet et COD ; dans le groupe nominal, différencier épithète et complément du nom', page: 20 },
  { id: 'c3.fr.langue.classes-de-mots', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONSTITUANTS, competence: 'Identifier les pronoms personnels et préciser leur fonction ; distinguer conjonction de coordination et conjonction de subordination (déterminants, adverbe, préposition : terminologie, p. 16)', page: 20 },
  { id: 'c3.fr.langue.phrase-complexe', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_COMPLEXE, competence: 'Distinguer phrase simple et phrase complexe par la notion de proposition ; approfondir juxtaposition, coordination et subordination', page: 20 },
  { id: 'c3.fr.langue.orthographe-grammaticale', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ORTHO_GRAM, competence: 'Améliorer son orthographe grammaticale dans le cadre de la production d’écrits ou d’exercices d’entraînement', page: 20 },
  { id: 'c3.fr.langue.accord-gn', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ORTHO_GRAM, competence: 'Maîtriser la chaîne d’accords dans le groupe nominal, en lien avec l’analyse grammaticale', page: 20 },
  { id: 'c3.fr.langue.accord-sujet-verbe', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_ORTHO_GRAM, competence: 'Identifier le groupe sujet et raisonner sur l’accord sujet-verbe', page: 20 },
  { id: 'c3.fr.langue.attribut-participe-etre', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONJUGAISON, competence: 'Maîtriser l’accord du participe passé employé avec l’auxiliaire être ; accord de l’attribut du sujet (CM2, p. 19)', page: 21 },
  { id: 'c3.fr.langue.participe-passe-avoir', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONJUGAISON, competence: 'Accorder le participe passé avec le COD pour les verbes étudiés conjugués avec avoir (pronom personnel antéposé)', page: 21 },
  { id: 'c3.fr.langue.temps-a-memoriser', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONJUGAISON, competence: 'Mémoriser l’impératif et le conditionnel présents, après le présent, l’imparfait, le futur, le passé composé (CM1) et le passé simple, le plus-que-parfait (CM2) : être, avoir, 1er et 2e groupes, faire, aller, dire, venir, pouvoir, voir, vouloir, prendre', page: 21 },
  { id: 'c3.fr.langue.valeurs-des-temps', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONJUGAISON, competence: 'S’initier aux valeurs des temps : temps du discours, puis temps du récit ; distinguer temps chronologique et temps verbal (p. 16)', page: 21 },
  { id: 'c3.fr.langue.finales-en-e', ...FR, cycle: 3, discipline: 'french', domaine: 'c3-fr-langue', attendu: FR_CONJUGAISON, competence: 'Écrire les formes verbales en /e/ (é, er, ez) : composition des temps composés (auxiliaire et participe passé), marques de temps et de personne ; le texte ne nomme ni ces finales ni la procédure de remplacement', page: 21 },
  // ---------- Mathématiques (programme de 2025, partie de 6e) ----------
  { id: 'c3.ma.nombres.calcul-mental', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_ENTIERS_DECIMAUX, competence: 'Automatismes : multiplier et diviser un décimal par 10, 100, 1 000 ; les procédures de calcul mental du cycle 2 et du cours moyen (doubles et moitiés, CM2, p. 11) sont entretenues', page: 13 },
  { id: 'c3.ma.nombres.grands-entiers', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_ENTIERS_DECIMAUX, competence: 'Connaître des grands nombres entiers (le milliard est introduit en 6e) ; la valeur des chiffres selon leur rang', page: 14 },
  { id: 'c3.ma.nombres.decimaux-ecritures', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_ENTIERS_DECIMAUX, competence: 'Liens entre unités de numération (dixième, centième, millième) ; écritures d’un décimal : à virgule, fraction, nombre mixte, pourcentage', page: 14 },
  { id: 'c3.ma.nombres.decimaux-comparer', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_ENTIERS_DECIMAUX, competence: 'Placer et repérer un décimal sur une demi-droite graduée ; comparer, ordonner, encadrer, intercaler des décimaux', page: 14 },
  { id: 'c3.ma.nombres.arrondi', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_ENTIERS_DECIMAUX, competence: 'Donner la valeur arrondie à l’unité, au dixième ou au centième d’un nombre décimal', page: 14 },
  { id: 'c3.ma.nombres.calcul-pose', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_ENTIERS_DECIMAUX, competence: 'Additionner et soustraire des décimaux ; division euclidienne d’un entier par un entier inférieur à 100 ; diviser un décimal par un entier inférieur à 10', page: 14 },
  { id: 'c3.ma.nombres.produit-decimaux', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_ENTIERS_DECIMAUX, competence: 'Comprendre le sens de la multiplication de deux décimaux, calculer leur produit ; contrôler par un ordre de grandeur', page: 14 },
  { id: 'c3.ma.nombres.problemes', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_ENTIERS_DECIMAUX, competence: 'Résoudre des problèmes mettant en jeu des multiplications de décimaux, des divisions décimales et euclidiennes', page: 14 },
  { id: 'c3.ma.nombres.faits-numeriques', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_FRACTIONS, competence: 'Automatismes : tables de multiplication, multiples et diviseurs réactivés pour calculer sur les fractions ; relations entre un quart, un demi, trois quarts et 1', page: 15 },
  { id: 'c3.ma.nombres.fractions-designations', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_FRACTIONS, competence: 'Relier une fraction au quotient de son numérateur par son dénominateur ; placer une fraction sur une demi-droite graduée ; appliquer une fraction à un entier', page: 15 },
  { id: 'c3.ma.nombres.fractions-comparer', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_FRACTIONS, competence: 'Établir des égalités de fractions ; comparer, encadrer, ordonner des fractions et des nombres mixtes', page: 16 },
  { id: 'c3.ma.nombres.fractions-operations', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_FRACTIONS, competence: 'Additionner et soustraire des fractions ; multiplier une fraction par un entier ; résoudre des problèmes avec des fractions', page: 16 },
  { id: 'c3.ma.nombres.pourcentages', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_FRACTIONS, competence: 'Comprendre le sens d’un pourcentage ; exprimer une proportion en pourcentage ; appliquer un pourcentage à une grandeur ou à un nombre', page: 16 },
  { id: 'c3.ma.nombres.algebre', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-nombres', attendu: MA_ALGEBRE, competence: 'Utiliser des modèles pré-algébriques (schémas en barre) ; identifier la structure d’un motif évolutif', page: 16 },
  { id: 'c3.ma.grandeurs.perimetre', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_LONGUEURS, competence: 'Calculer le périmètre d’un carré, d’un rectangle, d’un disque, de figures composées ; résoudre des problèmes de longueurs', page: 19 },
  { id: 'c3.ma.grandeurs.unites-conversions', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_LONGUEURS, competence: 'Connaître les préfixes du kilo au milli ; convertir une longueur en mètre et inversement', page: 19 },
  { id: 'c3.ma.grandeurs.aire', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_AIRES, competence: 'Comparer des aires ; aire d’un carré et d’un rectangle ; convertir des unités d’aire (1 m² = 100 dm²)', page: 19 },
  { id: 'c3.ma.grandeurs.volume', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_VOLUMES, competence: 'Connaître l’unité centimètre cube ; comparer et déterminer des volumes', page: 20 },
  { id: 'c3.ma.grandeurs.durees', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-grandeurs', attendu: MA_DUREES, competence: 'Lire l’heure ; connaître les unités de durée ; calculer sur des horaires et des durées ; convertir des durées', page: 20 },
  { id: 'c3.ma.espace.figures-solides', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_CONFIGURATIONS, competence: 'Reconnaître un carré, un rectangle, un triangle, les axes de symétrie d’une figure ; reconnaître pyramides, boules, cubes, cylindres, pavés, cônes, prismes droits (p. 24)', page: 23 },
  { id: 'c3.ma.espace.relations', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_CONFIGURATIONS, competence: 'Distance entre deux points, milieu d’un segment ; cercle et disque, rayon, diamètre, corde ; médiatrice d’un segment ; symétrie axiale', page: 23 },
  { id: 'c3.ma.espace.angles', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_CONFIGURATIONS, competence: 'Lexique des angles (droit, plat, aigu, obtus, opposés par le sommet, adjacents, supplémentaires) ; mesurer un angle ; bissectrice', page: 23 },
  { id: 'c3.ma.espace.triangles', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_CONFIGURATIONS, competence: 'Propriétés angulaires des triangles rectangle, isocèle et équilatéral ; somme des angles d’un triangle ; cercle circonscrit', page: 23 },
  { id: 'c3.ma.espace.construction', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_CONFIGURATIONS, competence: 'Construire un angle de mesure donnée, des triangles, le symétrique d’une figure ; reporter des longueurs au compas', page: 23 },
  { id: 'c3.ma.espace.vision-espace', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-espace', attendu: MA_VISION, competence: 'Voir dans l’espace des assemblages de cubes : passer de l’objet à ses représentations en deux dimensions, dénombrer', page: 24 },
  { id: 'c3.ma.donnees.donnees', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-donnees', attendu: MA_DONNEES, competence: 'Lire un tableau, un diagramme en barres ou circulaire, une courbe ; planifier une enquête, construire un tableau, filtrer les données selon un critère', page: 26 },
  { id: 'c3.ma.donnees.probabilites', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-donnees', attendu: MA_PROBABILITES, competence: 'Une probabilité est un nombre entre 0 et 1 ; calculer des probabilités en situation d’équiprobabilité ; comparer résultats observés et probabilité', page: 26 },
  { id: 'c3.ma.proportionnalite.proportionnalite', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-proportionnalite', attendu: MA_PROPORTIONNALITE, competence: 'Identifier une situation de proportionnalité entre deux grandeurs ; la résoudre par linéarité ou retour à l’unité, sans produit en croix ; la représenter par un tableau', page: 27 },
  { id: 'c3.ma.proportionnalite.echelle', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-proportionnalite', attendu: MA_PROPORTIONNALITE, competence: 'S’initier à la résolution de problèmes d’échelles', page: 27 },
  { id: 'c3.ma.informatique.programmation', ...MA, cycle: 3, discipline: 'maths', domaine: 'c3-ma-informatique', attendu: MA_INFORMATIQUE, competence: 'Identifier, produire, exécuter et répéter une séquence d’instructions ; programmer la construction d’un chemin simple', page: 28 },
  // ---------- Anglais (programme d’anglais des classes de collège, 2025, partie de 6e) ----------
  { id: 'c3.en.culture.personnes', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-culture', attendu: EN_AXES, competence: 'Axe 1, personnes et personnages : personnes et personnages emblématiques du monde anglophone, fictifs ou réels', page: 6 },
  { id: 'c3.en.culture.vie-quotidienne', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-culture', attendu: EN_AXES, competence: 'Axe 2, le quotidien (vivre, jouer, apprendre) : l’environnement quotidien des jeunes anglophones, à l’école et dans les loisirs', page: 6 },
  { id: 'c3.en.culture.reperes', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-culture', attendu: EN_AXES, competence: 'Axe 3, pays et paysages : repères visuels et géographiques sur le monde anglophone', page: 6 },
  { id: 'c3.en.culture.imaginaire', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-culture', attendu: EN_AXES, competence: 'Axe 4, imaginaire, contes et légendes : quelques motifs récurrents de la littérature de langue anglaise', page: 6 },
  { id: 'c3.en.culture.arts', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-culture', attendu: EN_AXES, competence: 'Axe 5, arts et expression des sentiments : découvrir des œuvres et dire ce qu’on en perçoit', page: 6 },
  { id: 'c3.en.ecouter.consignes', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-ecouter', attendu: EN_COMPRENDRE, competence: 'Suivre des consignes et des instructions habituelles, à condition que le débit soit lent et l’information claire', page: 7 },
  { id: 'c3.en.ecouter.mots-familiers', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-ecouter', attendu: EN_COMPRENDRE, competence: 'Comprendre des expressions isolées dans des énoncés très simples et concrets sur des sujets familiers ; s’appuyer sur les indices visuels et sonores et sur les mots familiers', page: 7 },
  { id: 'c3.en.ecouter.histoire', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-ecouter', attendu: EN_COMPRENDRE, competence: 'Comprendre des expressions isolées dans des histoires ; s’appuyer sur les répétitions de mots et de structures pour identifier les étapes du récit', page: 7 },
  { id: 'c3.en.lire.mots-isoles', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-lire', attendu: EN_COMPRENDRE, competence: 'S’appuyer sur les mots transparents ou familiers pour comprendre un mot nouveau ou le reconnaître', page: 7 },
  { id: 'c3.en.lire.textes-courts', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-lire', attendu: EN_COMPRENDRE, competence: 'Comprendre des documents écrits clairs et courts (consignes, informations, descriptions, dialogues) ; identifier quelques types de textes par leur mise en page', page: 7 },
  { id: 'c3.en.parler.reproduire-presenter', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-parler', attendu: EN_EXPRIMER, competence: 'Se présenter, décrire des personnes, des lieux et des objets, exprimer ses goûts, raconter brièvement ; lire de manière expressive un texte bref préparé', page: 8 },
  { id: 'c3.en.ecrire.phrases', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-ecrire', attendu: EN_EXPRIMER, competence: 'Rédiger de courts textes imitatifs ou en réponse à des documents travaillés ; compléter un questionnaire (p. 8)', page: 7 },
  { id: 'c3.en.ecrire.dictee', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-ecrire', attendu: EN_EXPRIMER, competence: 'Copier, recopier ; écrire sous la dictée des phrases très simples', page: 8 },
  { id: 'c3.en.dialoguer.renseignements', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-dialoguer', attendu: EN_INTERAGIR, competence: 'Poser quelques questions simples et y répondre ; transmettre les informations factuelles essentielles d’un prospectus, d’une invitation (lieu, horaire, prix, p. 10)', page: 9 },
  { id: 'c3.en.dialoguer.contact-social', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-dialoguer', attendu: EN_INTERAGIR, competence: 'Utiliser des formules de politesse élémentaires pour saluer, prendre congé, remercier, s’excuser ; demander des nouvelles', page: 10 },
  { id: 'c3.en.dialoguer.reagir', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-dialoguer', attendu: EN_INTERAGIR, competence: 'Faire part très simplement de son accord ou de son désaccord ; demander l’autorisation, de l’aide, de répéter', page: 10 },
  { id: 'c3.en.langue.phonologie', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_OUTILS, competence: 'Prononcer le -s de la 3e personne, du génitif et du pluriel ; accentuer les mots polysyllabiques ; intonation des énoncés affirmatifs et interrogatifs', page: 10 },
  { id: 'c3.en.langue.phonie-graphie', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_OUTILS, competence: 'Percevoir la relation entre graphie et phonie (consonnes muettes, diphtongues) ; épeler des mots (interaction)', page: 10 },
  { id: 'c3.en.langue.lexique', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_OUTILS, competence: 'Lexique des axes : famille, nationalités, apparence, vêtements, corps, animaux, quotidien, maison, loisirs, fêtes ; compter jusqu’à 100, dire l’heure (p. 12)', page: 10 },
  { id: 'c3.en.langue.groupe-verbal', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_OUTILS, competence: 'Le présent simple des verbes courants et les auxiliaires be et have ; la 3e personne du singulier ; can et can’t ; l’impératif', page: 12 },
  { id: 'c3.en.langue.groupe-nominal', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_OUTILS, competence: 'Articles a, the, Ø ; this, these, that, those ; accords élémentaires (there is, there are, pluriels irréguliers) ; possessifs et génitif ; pronoms personnels', page: 12 },
  { id: 'c3.en.langue.phrase', ...EN, cycle: 3, discipline: 'english', domaine: 'c3-en-langue', attendu: EN_OUTILS, competence: 'Former des phrases simples affirmatives et négatives avec not, interrogatives en A1+ ; and, but, or ; first, then ; mots interrogatifs (p. 12)', page: 13 },
  // ---------- Histoire et géographie (6e) ----------
  { id: 'c3.hg.temps.periodes', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-temps', attendu: HG_TEMPS, competence: 'Situer chronologiquement des grandes périodes historiques ; mémoriser les repères historiques liés au programme', page: 67 },
  { id: 'c3.hg.temps.ordonner', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-temps', attendu: HG_TEMPS, competence: 'Ordonner des faits les uns par rapport aux autres et les situer dans une époque ou une période donnée', page: 67 },
  { id: 'c3.hg.temps.frise', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-temps', attendu: HG_TEMPS, competence: 'Utiliser des documents donnant à voir une représentation du temps (dont les frises chronologiques), à différentes échelles, et le lexique relatif au découpage du temps', page: 67 },
  { id: 'c3.hg.espace.localiser', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-espace', attendu: HG_ESPACE, competence: 'Nommer et localiser les grands repères géographiques ; nommer et localiser un lieu dans un espace géographique ; mémoriser les repères géographiques liés au programme', page: 67 },
  { id: 'c3.hg.espace.situer', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-espace', attendu: HG_ESPACE, competence: 'Nommer, localiser et caractériser des espaces ; situer des lieux et des espaces les uns par rapport aux autres ; appréhender la notion d’échelle géographique', page: 67 },
  { id: 'c3.hg.demarches.document', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_DOC, competence: 'Comprendre le sens général d’un document ; identifier le document et savoir pourquoi il doit être identifié ; extraire des informations pertinentes pour répondre à une question', page: 68 },
  { id: 'c3.hg.demarches.point-de-vue', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_DOC, competence: 'Savoir que le document exprime un point de vue ; identifier et questionner son sens implicite', page: 68 },
  { id: 'c3.hg.demarches.lexique', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_LANGAGES, competence: 'S’approprier et utiliser un lexique historique et géographique approprié', page: 68 },
  { id: 'c3.hg.demarches.cartes', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_LANGAGES, competence: 'Utiliser des cartes analogiques et numériques à différentes échelles, des photographies de paysages ou de lieux ; réaliser ou compléter des productions graphiques', page: 68 },
  { id: 'c3.hg.demarches.ecrire-dire', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_LANGAGES, competence: 'Écrire pour structurer sa pensée et son savoir, pour argumenter et pour communiquer ; reconnaître un récit historique ; s’exprimer à l’oral pour penser, communiquer et échanger', page: 68 },
  { id: 'c3.hg.demarches.raisonner', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-demarches', attendu: HG_RAISONNER, competence: 'Poser des questions, se poser des questions ; formuler des hypothèses ; vérifier ; justifier ; s’informer dans le monde du numérique ; coopérer et mutualiser', page: 67 },
  { id: 'c3.hg.histoire.debuts-humanite', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H1, competence: 'Les débuts de l’humanité : premiers humains, peuplement de la Terre, grandes migrations', page: 71 },
  { id: 'c3.hg.histoire.neolithique', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H1, competence: 'La « révolution » néolithique : agriculture, élevage, sédentarisation', page: 71 },
  { id: 'c3.hg.histoire.premiers-etats', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H1, competence: 'Premiers États, premières écritures', page: 71 },
  { id: 'c3.hg.histoire.cites-grecques', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H2, competence: 'Le monde des cités grecques : l’univers culturel commun des Grecs vivant dans des cités rivales ; la naissance de la démocratie à Athènes', page: 72 },
  { id: 'c3.hg.histoire.rome-mythe', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H2, competence: 'Rome du mythe à l’histoire : le mythe de sa fondation, qui permet à Rome d’asseoir sa domination', page: 72 },
  { id: 'c3.hg.histoire.monotheisme-juif', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H2, competence: 'La naissance du monothéisme juif dans un monde polythéiste', page: 72 },
  { id: 'c3.hg.histoire.empire-romain', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H3, competence: 'Conquêtes, paix romaine et romanisation', page: 72 },
  { id: 'c3.hg.histoire.chretiens', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H3, competence: 'Des chrétiens dans l’empire', page: 72 },
  { id: 'c3.hg.histoire.route-de-la-soie', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-histoire', attendu: HG_H3, competence: 'Les relations de l’empire romain avec les autres mondes anciens : l’ancienne route de la soie et la Chine des Han', page: 72 },
  { id: 'c3.hg.geographie.metropoles', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G1, competence: 'Les métropoles et leurs habitants', page: 75 },
  { id: 'c3.hg.geographie.ville-de-demain', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G1, competence: 'La ville de demain', page: 75 },
  { id: 'c3.hg.geographie.contraintes', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G2, competence: 'Habiter un espace à forte(s) contrainte(s) naturelle(s) ou/et de grande biodiversité', page: 76 },
  { id: 'c3.hg.geographie.agricole', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G2, competence: 'Habiter un espace de faible densité à vocation agricole', page: 76 },
  { id: 'c3.hg.geographie.littoral-portuaire', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G3, competence: 'Un littoral industrialo-portuaire', page: 76 },
  { id: 'c3.hg.geographie.littoral-touristique', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G3, competence: 'Un littoral touristique', page: 76 },
  { id: 'c3.hg.geographie.population-mondiale', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G4, competence: 'La répartition de la population mondiale et ses dynamiques', page: 76 },
  { id: 'c3.hg.geographie.occupation', ...HG, cycle: 3, discipline: 'history-geography', domaine: 'c3-hg-geographie', attendu: HG_G4, competence: 'La variété des formes d’occupation spatiale dans le monde', page: 76 },
  // ---------- SVT (sciences et technologie, 6e : programme du cycle 3 en vigueur à la rentrée 2023) ----------
  { id: 'c3.sv.demarches.observer', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_DEMARCHE, competence: 'Formuler une question ou une hypothèse ; proposer ou suivre un protocole ; utiliser des instruments d’observation ; interpréter des résultats et en tirer des conclusions', page: 80 },
  { id: 'c3.sv.demarches.langages', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_LANGAGES, competence: 'Exploiter un document constitué de divers supports (texte, schéma, graphique, tableau, carte heuristique) ; passer d’une représentation à une autre ; rendre compte avec un vocabulaire précis', page: 80 },
  { id: 'c3.sv.demarches.responsable', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_RESPONSABLE, competence: 'Relier des connaissances acquises en sciences et technologie à des questions de santé, de sécurité et d’environnement ; comprendre et expliquer des décisions collectives et responsables', page: 81 },
  { id: 'c3.sv.demarches.situer', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_SITUER, competence: 'Maîtriser les notions d’échelle spatiale et temporelle et en citer quelques ordres de grandeur ; identifier comment se construit un savoir scientifique dans son contexte', page: 81 },
  { id: 'c3.sv.demarches.esprit-critique', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-demarches', attendu: ST_CRITIQUE, competence: 'Identifier des sources d’informations fiables ; vérifier l’existence de preuves ; évaluer la pertinence des arguments ; distinguer une croyance d’un savoir scientifique', page: 81 },
  { id: 'c3.sv.vivant.cellule', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_PANORAMA, competence: 'Les niveaux d’organisation d’un être vivant (organisme, appareil, organe) ; observer des cellules au microscope ; la cellule, unité structurale commune à tous les êtres vivants', page: 88 },
  { id: 'c3.sv.vivant.classer', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_PANORAMA, competence: 'Classer en groupes emboîtés et établir des parentés à partir des attributs ; lire des arbres de parenté simples ; les différents types de classification et leurs objectifs', page: 88 },
  { id: 'c3.sv.vivant.evolution', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_PANORAMA, competence: 'La biodiversité actuelle et passée : la diversité au sein d’une espèce, les clés de détermination, les fossiles et les paléoenvironnements, les grandes crises biologiques sur une échelle des temps', page: 88 },
  { id: 'c3.sv.vivant.alimentation', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_ALIMENTS, competence: 'Les besoins alimentaires et des comportements favorables à la santé ; la diversité des aliments selon les cultures ; conserver les aliments pour limiter les risques sanitaires ; les microorganismes et la fermentation', page: 89 },
  { id: 'c3.sv.vivant.developpement', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-vivant', attendu: SV_CYCLE, competence: 'Les étapes d’un cycle de vie ; la pollinisation, de la fleur au fruit ; la puberté ; les organes reproducteurs, la fécondation et le développement de l’être humain', page: 90 },
  { id: 'c3.sv.terre.systeme-solaire', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_TERRE, competence: 'Situer la Terre dans le système solaire ; les conditions qui permettent la vie sur Terre : atmosphère et température compatibles avec la vie, présence d’eau liquide', page: 96 },
  { id: 'c3.sv.terre.phenomenes', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_TERRE, competence: 'Les indices de l’activité interne ou externe de la Terre (séismes, volcans, vents, courants océaniques) ; distinguer la météorologie du climat ; un risque naturel et sa prévention ; des ressources liées à l’activité de la Terre', page: 96 },
  { id: 'c3.sv.terre.climat', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_TERRE, competence: 'Le réchauffement climatique récent : argumenter à partir de données, le relier aux gaz à effet de serre émis par les activités humaines ; ses conséquences sur le peuplement des milieux ; atténuation et adaptation', page: 96 },
  { id: 'c3.sv.terre.peuplement', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_ECOSYSTEME, competence: 'Un écosystème : milieu de vie, êtres vivants et relations entre espèces ; relier le peuplement d’un milieu à ses conditions et aux saisons ; les adaptations à la mauvaise saison ; les effets d’une perturbation', page: 97 },
  { id: 'c3.sv.terre.chaines-alimentaires', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_ECOSYSTEME, competence: 'Les besoins des végétaux (lumière, eau, sels minéraux, dioxyde de carbone) et leur place à la base des chaînes alimentaires ; les réseaux alimentaires ; la décomposition de la matière organique par les êtres vivants du sol', page: 97 },
  { id: 'c3.sv.terre.environnement', ...ST, cycle: 3, discipline: 'life-earth-sciences', domaine: 'c3-sv-terre', attendu: SV_ECOSYSTEME, competence: 'Les répercussions positives et négatives des actions humaines sur l’environnement ; une exploitation raisonnée des ressources ; des actions et des objets qui favorisent la biodiversité', page: 98 },
  // ---------- Physique-chimie (sciences et technologie, 6e : programme du cycle 3 en vigueur à la rentrée 2023) ----------
  { id: 'c3.pc.demarches.experimenter', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-demarches', attendu: ST_DEMARCHE, competence: 'Formuler une question ou une hypothèse ; concevoir et mettre en œuvre une expérience pour la tester ; interpréter les résultats et en tirer des conclusions', page: 80 },
  { id: 'c3.pc.demarches.mesurer', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-demarches', attendu: ST_DEMARCHE, competence: 'Utiliser des instruments d’observation et de mesure ; étudier les phénomènes en mobilisant des grandeurs physiques', page: 80 },
  { id: 'c3.pc.demarches.langages', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-demarches', attendu: ST_LANGAGES, competence: 'Exploiter un document constitué de divers supports (texte, schéma, graphique, tableau) ; utiliser différents modes de représentation et passer de l’un à l’autre ; rendre compte avec un vocabulaire précis', page: 80 },
  { id: 'c3.pc.matiere.etats', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATIERE, competence: 'Les états solide, liquide et gazeux ; les changements d’état et leur réversibilité ; les températures de changement d’état et les paliers de température', page: 82 },
  { id: 'c3.pc.matiere.grandeurs', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATIERE, competence: 'Masse et volume : les mesurer (balance, déplacement de liquide), convertir leurs unités ; la proportionnalité entre la masse et le volume d’un corps homogène', page: 82 },
  { id: 'c3.pc.matiere.materiaux', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATERIAUX, competence: 'Comparer et trier des matériaux selon leurs propriétés physiques (conductivité thermique ou électrique, capacité à interagir avec un aimant) ; leur durée de décomposition dans la nature', page: 82 },
  { id: 'c3.pc.matiere.melanges', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATIERE, competence: 'Séparer les constituants d’un mélange (tamisage, décantation, filtration, évaporation) ; la dissolution et la saturation ; la masse totale se conserve ; les liquides non miscibles', page: 83 },
  { id: 'c3.pc.matiere.transformations', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MATIERE, competence: 'Un mélange qui produit une transformation chimique (changement de couleur, gaz) ; la sécurité des produits ménagers et les pictogrammes de danger ; la composition de l’air et les gaz à effet de serre', page: 83 },
  { id: 'c3.pc.matiere.mouvements', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_MOUVEMENT, competence: 'Mouvement rectiligne ou circulaire, par rapport à un observateur ; vitesse constante ou variable ; calculer la vitesse d’un mouvement uniforme ; l’année et la révolution de la Terre, le jour et sa rotation', page: 84 },
  { id: 'c3.pc.matiere.energie', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_ENERGIE, competence: 'Les formes d’énergie (de pesanteur, cinétique, chimique, thermique, électrique, nucléaire, lumineuse) ; une chaîne énergétique ; les ressources renouvelables ou non, et les conséquences de leur utilisation sur l’environnement', page: 85 },
  { id: 'c3.pc.matiere.lumiere', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_OMBRES, competence: 'Interpréter l’alternance du jour et de la nuit à l’aide d’un modèle ; associer les saisons à l’inclinaison du Soleil et à la durée du jour pour un observateur sur la Terre', page: 86 },
  { id: 'c3.pc.matiere.circuit', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_CIRCUIT, competence: 'Le circuit électrique à une boucle, avec un convertisseur d’énergie ou un capteur ; sa représentation schématique normalisée ; la conductivité électrique des matériaux ; les règles de sécurité électrique', page: 86 },
  { id: 'c3.pc.matiere.signal', ...ST, cycle: 3, discipline: 'physics-chemistry', domaine: 'c3-pc-matiere', attendu: PC_SIGNAL, competence: 'Identifier différents signaux pour transmettre de l’information (signal sonore, lumineux, électrique) ; citer quelques applications', page: 87 },
  // ---------- Technologie (sciences et technologie, 6e : programme du cycle 3 en vigueur à la rentrée 2023) ----------
  // En 6e, la partie « Les objets techniques au cœur de la société » ne fixe que des attendus de fin de cours moyen,
  // repris en sixième par leurs liens avec les autres thèmes (pages 91 à 95) : les compétences les résument ensemble.
  { id: 'c3.te.demarches.concevoir', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-demarches', attendu: ST_CONCEVOIR, competence: 'Imaginer un objet technique en réponse à un besoin ; concevoir et réaliser une maquette pour modéliser un phénomène naturel ou un objet technique', page: 80 },
  { id: 'c3.te.demarches.representer', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-demarches', attendu: ST_LANGAGES, competence: 'Utiliser différents modes de représentation (schéma, dessin, croquis, tableau, texte) et passer de l’un à l’autre ; rendre compte avec un vocabulaire précis', page: 80 },
  { id: 'c3.te.demarches.numerique', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-demarches', attendu: ST_NUMERIQUE, competence: 'Utiliser des outils numériques pour communiquer des résultats, faire des recherches, traiter des données, simuler des phénomènes', page: 80 },
  { id: 'c3.te.objets.evolution', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_BESOIN, competence: 'Les besoins (se déplacer, se chauffer, s’alimenter) et leur évolution ; les évolutions d’un objet selon le contexte (historique, géographique, économique, culturel, technologique) ; les détournements d’usage', page: 91 },
  { id: 'c3.te.objets.fonction', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_FONCTIONNEMENT, competence: 'Distinguer un objet technique d’un objet naturel ; distinguer le besoin et les fonctions techniques d’un objet ; associer les solutions technologiques aux fonctions techniques', page: 91 },
  { id: 'c3.te.objets.fonctionnement', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_FONCTIONNEMENT, competence: 'Identifier les sous-ensembles d’un objet et décrire son fonctionnement par un schéma ; les mouvements de ses parties (poulies, engrenages) et les conversions d’énergie qu’il réalise', page: 92 },
  { id: 'c3.te.objets.materiaux', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_FONCTIONNEMENT, competence: 'Identifier les matériaux d’un objet ; choisir un matériau selon ses propriétés physiques (thermiques, électriques), en lien avec les propriétés de la matière', page: 92 },
  { id: 'c3.te.objets.probleme', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_CONCEPTION, competence: 'Rechercher des idées de solutions à un problème technique par des croquis ou des schémas ; comparer des solutions par une analyse critique ; prendre en compte une contrainte (imperméabilité, poids, autonomie)', page: 93 },
  { id: 'c3.te.objets.recyclage', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_CONCEPTION, competence: 'Les étapes du cycle de vie d’un objet technique ; des choix raisonnés selon leurs conséquences sur l’environnement, en lien avec la décomposition des matériaux', page: 94 },
  { id: 'c3.te.objets.realiser', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_CONCEPTION, competence: 'Organiser et planifier en équipe la réalisation d’une maquette ; réaliser des maquettes simples pour matérialiser une solution ; vérifier qu’elle répond au problème posé', page: 94 },
  { id: 'c3.te.objets.information', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_PROGRAMMATION, competence: 'Les objets reliés entre eux par des réseaux (objets communicants, transmission et traitement de données) ; la chaîne d’information et d’action d’un objet programmable, ses capteurs et ses actionneurs', page: 94 },
  { id: 'c3.te.objets.programmer', ...ST, cycle: 3, discipline: 'technology', domaine: 'c3-te-objets', attendu: TE_PROGRAMMATION, competence: 'Coder un algorithme simple qui agit sur un objet technique (programmation par blocs) ; comprendre un programme simple et le traduire en langage naturel ; critiquer un programme', page: 95 },
] as const satisfies readonly ProgrammeEntry[];
