// Cycle 4 (5e, 4e, 3e) : le programme en vigueur à la rentrée 2020 (annexe 3), résumé au grain d'une mission.
// Le texte ne répartit rien par année (sauf l'histoire et la géographie, thème par thème) : une compétence du cycle 4
// peut être travaillée en 5e, en 4e ou en 3e.
// Les libellés sont des résumés fidèles du texte officiel ; le texte fait foi (page du PDF indiquée).
import type { ProgrammeDomaine, ProgrammeEntry } from './types';

export const DOMAINES_C4: readonly ProgrammeDomaine[] = [
  { id: 'c4-fr-oral', cycle: 4, discipline: 'french', title: 'Langage oral', page: 12 },
  { id: 'c4-fr-lecture', cycle: 4, discipline: 'french', title: 'Lecture et compréhension de l’écrit et de l’image', page: 14 },
  { id: 'c4-fr-ecriture', cycle: 4, discipline: 'french', title: 'Écriture', page: 17 },
  { id: 'c4-fr-langue', cycle: 4, discipline: 'french', title: 'Étude de la langue (grammaire, orthographe, lexique)', page: 20 },
  { id: 'c4-fr-culture', cycle: 4, discipline: 'french', title: 'Culture littéraire et artistique', page: 27 },
  { id: 'c4-ma-a', cycle: 4, discipline: 'maths', title: 'Thème A – Nombres et calculs', page: 130 },
  { id: 'c4-ma-b', cycle: 4, discipline: 'maths', title: 'Thème B – Organisation et gestion de données, fonctions', page: 132 },
  { id: 'c4-ma-c', cycle: 4, discipline: 'maths', title: 'Thème C – Grandeurs et mesures', page: 134 },
  { id: 'c4-ma-d', cycle: 4, discipline: 'maths', title: 'Thème D – Espace et géométrie', page: 135 },
  { id: 'c4-ma-e', cycle: 4, discipline: 'maths', title: 'Thème E – Algorithmique et programmation', page: 136 },
  { id: 'c4-en-ecouter', cycle: 4, discipline: 'english', title: 'Langues vivantes : écouter et comprendre', page: 37 },
  { id: 'c4-en-lire', cycle: 4, discipline: 'english', title: 'Langues vivantes : lire', page: 38 },
  { id: 'c4-en-dialoguer', cycle: 4, discipline: 'english', title: 'Langues vivantes : réagir et dialoguer', page: 40 },
  { id: 'c4-en-parler', cycle: 4, discipline: 'english', title: 'Langues vivantes : parler en continu', page: 41 },
  { id: 'c4-en-ecrire', cycle: 4, discipline: 'english', title: 'Langues vivantes : écrire et réagir à l’écrit', page: 42 },
  { id: 'c4-en-culture', cycle: 4, discipline: 'english', title: 'Langues vivantes : connaissances culturelles', page: 43 },
  { id: 'c4-en-langue', cycle: 4, discipline: 'english', title: 'Langues vivantes : grammaire, lexique et phonologie', page: 44 },
  { id: 'c4-de-ecouter', cycle: 4, discipline: 'german', title: 'Langues vivantes : écouter et comprendre', page: 37 },
  { id: 'c4-de-lire', cycle: 4, discipline: 'german', title: 'Langues vivantes : lire', page: 38 },
  { id: 'c4-de-dialoguer', cycle: 4, discipline: 'german', title: 'Langues vivantes : réagir et dialoguer', page: 40 },
  { id: 'c4-de-parler', cycle: 4, discipline: 'german', title: 'Langues vivantes : parler en continu', page: 41 },
  { id: 'c4-de-ecrire', cycle: 4, discipline: 'german', title: 'Langues vivantes : écrire et réagir à l’écrit', page: 42 },
  { id: 'c4-de-culture', cycle: 4, discipline: 'german', title: 'Langues vivantes : connaissances culturelles', page: 43 },
  { id: 'c4-de-langue', cycle: 4, discipline: 'german', title: 'Langues vivantes : grammaire, lexique et phonologie', page: 44 },
  { id: 'c4-es-ecouter', cycle: 4, discipline: 'spanish', title: 'Langues vivantes : écouter et comprendre', page: 37 },
  { id: 'c4-es-lire', cycle: 4, discipline: 'spanish', title: 'Langues vivantes : lire', page: 38 },
  { id: 'c4-es-dialoguer', cycle: 4, discipline: 'spanish', title: 'Langues vivantes : réagir et dialoguer', page: 40 },
  { id: 'c4-es-parler', cycle: 4, discipline: 'spanish', title: 'Langues vivantes : parler en continu', page: 41 },
  { id: 'c4-es-ecrire', cycle: 4, discipline: 'spanish', title: 'Langues vivantes : écrire et réagir à l’écrit', page: 42 },
  { id: 'c4-es-culture', cycle: 4, discipline: 'spanish', title: 'Langues vivantes : connaissances culturelles', page: 43 },
  { id: 'c4-es-langue', cycle: 4, discipline: 'spanish', title: 'Langues vivantes : grammaire, lexique et phonologie', page: 44 },
  // Histoire et géographie : pages et libellés vérifiés dans le PDF cité par sources.ts (7 octobre 2026). Le texte répartit les thèmes par classe : chaque thème est une compétence, donc une mission.
  // L'enseignement moral et civique, qui suit dans le PDF, n'est pas dans l'application (hors périmètre).
  { id: 'c4-hg-temps', cycle: 4, discipline: 'history-geography', title: 'Histoire et géographie : se repérer dans le temps', page: 78 },
  { id: 'c4-hg-espace', cycle: 4, discipline: 'history-geography', title: 'Histoire et géographie : se repérer dans l’espace', page: 79 },
  { id: 'c4-hg-demarches', cycle: 4, discipline: 'history-geography', title: 'Histoire et géographie : raisonner, analyser et comprendre un document, pratiquer différents langages', page: 79 },
  { id: 'c4-hg-histoire', cycle: 4, discipline: 'history-geography', title: 'Histoire, classes de cinquième, quatrième et troisième', page: 80 },
  { id: 'c4-hg-geographie', cycle: 4, discipline: 'history-geography', title: 'Géographie, classes de cinquième, quatrième et troisième', page: 85 },
  // Physique-chimie, SVT et technologie : trois enseignements distincts au cycle 4, dans cet ordre dans le PDF, avant
  // les mathématiques. Écrits de mémoire, au plus près du texte, et pages estimées (le site du ministère et celui de
  // data.gouv.fr sont refusés depuis l'environnement de travail, 6 octobre 2026) : à relire dans le PDF avant la
  // première île de 5e. Le texte ne répartit pas ces programmes par classe. Les compétences travaillées (démarches,
  // langages, outils, responsabilité) sont communes aux trois : chaque discipline reprend celles qu'elle travaille.
  { id: 'c4-pc-demarches', cycle: 4, discipline: 'physics-chemistry', title: 'Physique-chimie : compétences travaillées', page: 100, unverified: true },
  { id: 'c4-pc-matiere', cycle: 4, discipline: 'physics-chemistry', title: 'Organisation et transformations de la matière', page: 102, unverified: true },
  { id: 'c4-pc-mouvement', cycle: 4, discipline: 'physics-chemistry', title: 'Mouvement et interactions', page: 105, unverified: true },
  { id: 'c4-pc-energie', cycle: 4, discipline: 'physics-chemistry', title: 'L’énergie et ses conversions', page: 106, unverified: true },
  { id: 'c4-pc-signaux', cycle: 4, discipline: 'physics-chemistry', title: 'Des signaux pour observer et communiquer', page: 108, unverified: true },
  { id: 'c4-sv-demarches', cycle: 4, discipline: 'life-earth-sciences', title: 'Sciences de la vie et de la Terre : compétences travaillées', page: 110, unverified: true },
  { id: 'c4-sv-terre', cycle: 4, discipline: 'life-earth-sciences', title: 'La planète Terre, l’environnement et l’action humaine', page: 112, unverified: true },
  { id: 'c4-sv-vivant', cycle: 4, discipline: 'life-earth-sciences', title: 'Le vivant et son évolution', page: 115, unverified: true },
  { id: 'c4-sv-corps', cycle: 4, discipline: 'life-earth-sciences', title: 'Le corps humain et la santé', page: 117, unverified: true },
  { id: 'c4-te-demarches', cycle: 4, discipline: 'technology', title: 'Technologie : compétences travaillées', page: 120, unverified: true },
  { id: 'c4-te-design', cycle: 4, discipline: 'technology', title: 'Design, innovation et créativité', page: 122, unverified: true },
  { id: 'c4-te-objets', cycle: 4, discipline: 'technology', title: 'Les objets techniques, les services et les changements induits dans la société', page: 123, unverified: true },
  { id: 'c4-te-modelisation', cycle: 4, discipline: 'technology', title: 'La modélisation et la simulation des objets et systèmes techniques', page: 124, unverified: true },
  { id: 'c4-te-informatique', cycle: 4, discipline: 'technology', title: 'L’informatique et la programmation', page: 126, unverified: true },
];

const FR_L1 = 'Lire et comprendre en autonomie des textes variés, des images et des documents composites, sur différents supports';
const FR_L2 = 'Lire, comprendre et interpréter des textes littéraires en fondant l’interprétation sur quelques outils d’analyse simples';
const FR_L3 = 'Situer les textes littéraires dans leur contexte historique et culturel';
const FR_A1 = 'Mobiliser les connaissances orthographiques, syntaxiques et lexicales en expression écrite et orale ainsi qu’en révision de texte';
const FR_A2 = 'Être capable d’analyser les principaux constituants d’une phrase simple et complexe';
const FR_A3 = 'Être capable d’orthographier les mots d’usage courant, de conjuguer correctement les verbes, de pratiquer les accords dans le groupe nominal';
const MA_A1 = 'Utiliser les nombres pour comparer, calculer et résoudre des problèmes';
const MA_A2 = 'Comprendre et utiliser les notions de divisibilité et de nombres premiers';
const MA_A3 = 'Utiliser le calcul littéral';
const MA_B1 = 'Interpréter, représenter et traiter des données';
const MA_B2 = 'Comprendre et utiliser des notions élémentaires de probabilités';
const MA_B3 = 'Résoudre des problèmes de proportionnalité';
const MA_B4 = 'Comprendre et utiliser la notion de fonction';
const MA_C1 = 'Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées';
const MA_C2 = 'Comprendre l’effet de quelques transformations sur les figures géométriques';
const MA_D1 = 'Représenter l’espace';
const MA_D2 = 'Utiliser les notions de géométrie plane pour démontrer';
// Langues vivantes : le programme du cycle 4 est commun à toutes les langues (anglais, et allemand ou espagnol en LV2).
const LV_ECOUTER = 'A1 : comprendre des mots familiers et des expressions courantes sur soi, sa famille et son environnement ; A2 : comprendre une intervention brève si elle est claire et simple ; B1 : comprendre une information factuelle sur des sujets simples';
const LV_LIRE = 'A1 : comprendre des textes très courts et très simples ; A2 : comprendre de courts textes simples sur des sujets concrets courants ; B1 : lire des textes factuels directs';
const LV_DIALOGUER = 'A1 : interagir brièvement dans des situations déjà connues ; A2 : interagir avec une aisance raisonnable dans des situations bien structurées ; B1 : exprimer un avis, manifester un sentiment';
const LV_PARLER = 'A1 : produire des expressions simples sur les gens et les choses ; A2 : décrire ou présenter simplement des gens, des activités, ce qu’on aime ; B1 : mener une description directe de sujets variés';
const LV_ECRIRE = 'A1 : écrire des expressions et phrases simples isolées ; A2 : écrire une série de phrases simples reliées par des connecteurs (et, mais, parce que) ; B1 : écrire un énoncé simple sur des sujets familiers';
const LV_CULTURE = 'Percevoir les spécificités culturelles des pays et des régions de la langue étudiée ; mobiliser des références culturelles pour interpréter un message, un texte, un document sonore';
const LV_LANGUE = 'Mobiliser à bon escient ses connaissances lexicales, culturelles et grammaticales pour comprendre et produire';

const HG_TEMPS = 'Se repérer dans le temps : construire des repères historiques';
const HG_ESPACE = 'Se repérer dans l’espace : construire des repères géographiques';
const HG_RAISONNER = 'Raisonner, justifier une démarche et les choix effectués';
const HG_DOC = 'Analyser et comprendre un document';
const HG_LANGAGES = 'Pratiquer différents langages en histoire et en géographie';
const HG_5H = 'Histoire, classe de 5e';
const HG_5G = 'Géographie, classe de 5e';
const HG_4H = 'Histoire, classe de 4e';
const HG_4G = 'Géographie, classe de 4e';
const HG_3H = 'Histoire, classe de 3e';
const HG_3G = 'Géographie, classe de 3e';
// Physique-chimie, SVT et technologie : les compétences travaillées, communes aux trois enseignements.
const ST_DEMARCHE = 'Pratiquer des démarches scientifiques et technologiques';
const ST_OUTILS = 'S’approprier des outils et des méthodes ; concevoir, créer, réaliser';
const ST_LANGAGES = 'Pratiquer des langages';
const ST_RESPONSABLE = 'Adopter un comportement éthique et responsable';
const PC_CONSTITUTION = 'Décrire la constitution et les états de la matière';
const PC_TRANSFORMATIONS = 'Décrire et expliquer des transformations chimiques';
const PC_UNIVERS = 'Décrire l’organisation de la matière dans l’Univers';
const PC_MOUVEMENT = 'Caractériser un mouvement';
const PC_FORCE = 'Modéliser une interaction par une force caractérisée par un point d’application, une direction, un sens et une valeur';
const PC_ENERGIE = 'Identifier les sources, les transferts, les conversions et les formes d’énergie ; utiliser la conservation de l’énergie';
const PC_ELECTRICITE = 'Réaliser des circuits électriques simples et exploiter les lois de l’électricité';
const PC_SIGNAUX = 'Caractériser différents types de signaux (lumineux, sonores, radio) ; utiliser les propriétés de ces signaux';
const SV_GEOLOGIE = 'Expliquer quelques phénomènes géologiques à partir du contexte géodynamique global';
const SV_CLIMAT = 'Expliquer quelques phénomènes météorologiques et climatiques';
const SV_ACTION = 'Identifier les principaux impacts de l’action humaine, bénéfices et risques, à la surface de la planète Terre ; envisager ou justifier des comportements responsables face à l’environnement et à la préservation des ressources limitées de la planète';
const SV_VIVANT = 'Expliquer l’organisation du monde vivant, sa structure et son dynamisme à différentes échelles d’espace et de temps';
const SV_CAUSALITE = 'Mettre en relation différents faits et établir des relations de causalité pour expliquer la diversité génétique des individus, la biodiversité, la classification et l’évolution des êtres vivants';
const SV_CORPS = 'Expliquer quelques processus biologiques impliqués dans le fonctionnement de l’organisme humain ; les relier aux enjeux des comportements responsables, individuels et collectifs, en matière de santé';
const TE_DESIGN = 'Imaginer des solutions en réponse aux besoins, matérialiser des idées en intégrant une dimension design';
const TE_PROJET = 'Réaliser, de manière collaborative, le prototype de tout ou partie d’un objet pour valider une solution';
const TE_OBJETS = 'Comparer et commenter les évolutions des objets et systèmes ; exprimer sa pensée à l’aide d’outils de description adaptés ; développer les bonnes pratiques de l’usage des objets communicants';
const TE_ANALYSER = 'Analyser le fonctionnement et la structure d’un objet';
const TE_SIMULER = 'Utiliser une modélisation et simuler le comportement d’un objet';
const TE_RESEAU = 'Comprendre le fonctionnement d’un réseau informatique';
const TE_PROGRAMMER = 'Écrire, mettre au point et exécuter un programme';

export const ENTRIES_C4 = [
  // ---------- Français ----------
  { id: 'c4.fr.oral.comprendre-s-exprimer', cycle: 4, discipline: 'french', domaine: 'c4-fr-oral', attendu: 'Comprendre et interpréter des messages et des discours oraux complexes ; s’exprimer de façon maîtrisée en s’adressant à un auditoire', competence: 'Langage oral : écouter, présenter, débattre, lire à voix haute', page: 12 },
  { id: 'c4.fr.lecture.controle', cycle: 4, discipline: 'french', domaine: 'c4-fr-lecture', attendu: FR_L1, competence: 'Contrôler sa compréhension : repérer les substituts du nom, élucider le sens des mots en contexte, formuler des hypothèses de lecture et chercher des indices', page: 15 },
  { id: 'c4.fr.lecture.documents', cycle: 4, discipline: 'french', domaine: 'c4-fr-lecture', attendu: FR_L1, competence: 'Lire des textes non littéraires et des documents composites : article de presse, texte documentaire, schéma, graphique, tableau ; identifier leur nature et leur source', page: 15 },
  { id: 'c4.fr.lecture.image', cycle: 4, discipline: 'french', domaine: 'c4-fr-lecture', attendu: FR_L1, competence: 'Décrire et analyser une image fixe ou mobile (peinture, photographie, dessin de presse, cinéma)', page: 15 },
  { id: 'c4.fr.lecture.genres-epoques', cycle: 4, discipline: 'french', domaine: 'c4-fr-lecture', attendu: FR_L3, competence: 'Lire des œuvres de différents genres et de différentes époques ; situer une œuvre dans son contexte de création', page: 16 },
  { id: 'c4.fr.lecture.procedes', cycle: 4, discipline: 'french', domaine: 'c4-fr-lecture', attendu: FR_L2, competence: 'Percevoir les effets de la langue littéraire ; analyser les procédés stylistiques et l’énonciation d’un texte', page: 16 },
  { id: 'c4.fr.ecriture.rediger', cycle: 4, discipline: 'french', domaine: 'c4-fr-ecriture', attendu: 'Communiquer par écrit et sur des supports variés un texte cohérent ; adopter des stratégies d’écriture efficaces', competence: 'Écriture : rédiger des écrits variés, réviser et améliorer son texte', page: 17 },
  { id: 'c4.fr.langue.oral-ecrit', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A1, competence: 'Connaître les différences entre l’oral et l’écrit : liaison, élision, écarts de niveau de langue', page: 21 },
  { id: 'c4.fr.langue.discours-rapporte', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A1, competence: 'Insérer et reconnaître des paroles rapportées : discours direct, indirect, indirect libre', page: 21 },
  { id: 'c4.fr.langue.sujet-complements', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A2, competence: 'Reconnaître le sujet même éloigné ; approfondir le COD et le COI ; identifier les compléments circonstanciels', page: 22 },
  { id: 'c4.fr.langue.fonctions-etendues', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A2, competence: 'Identifier l’attribut du COD, les expansions du nom (épithète, complément du nom) et l’apposition ; analyser la phrase impersonnelle', page: 22 },
  { id: 'c4.fr.langue.classes-de-mots', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A2, competence: 'Identifier les classes de mots : tous les déterminants et pronoms, l’adjectif et ses degrés, l’adverbe, la préposition, les conjonctions', page: 22 },
  { id: 'c4.fr.langue.types-formes', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A2, competence: 'Identifier les types (déclaratif, interrogatif, impératif) et les formes de phrase (négative, passive, exclamative, impersonnelle)', page: 22 },
  { id: 'c4.fr.langue.phrase-complexe', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A2, competence: 'Distinguer phrase simple et phrase complexe ; juxtaposition, coordination, subordination ; identifier les propositions', page: 23 },
  { id: 'c4.fr.langue.subordonnees', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A2, competence: 'Analyser les subordonnées (conjonctive, interrogative indirecte, relative, infinitive, participiale) ; identifier la fonction du pronom relatif', page: 23 },
  { id: 'c4.fr.langue.ponctuation', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A2, competence: 'Analyser le rôle syntaxique des signes de ponctuation et les utiliser à bon escient', page: 23 },
  { id: 'c4.fr.langue.accord-gn-complexe', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A3, competence: 'Maîtriser l’accord dans le groupe nominal complexe (plusieurs noms, plusieurs adjectifs, une relative, des déterminants comme tout, chaque, leur)', page: 23 },
  { id: 'c4.fr.langue.participe-passe', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A3, competence: 'Maîtriser l’accord du participe passé avec être et avec avoir (COD antéposé, cas simples), et de l’adjectif ou du participe mis en apposition', page: 23 },
  { id: 'c4.fr.langue.accord-verbe-complexe', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A3, competence: 'Maîtriser l’accord du verbe dans les cas complexes : sujet éloigné, plusieurs sujets, plusieurs personnes, pronom relatif, collectif ou distributif', page: 23 },
  { id: 'c4.fr.langue.morphologie-verbale', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A3, competence: 'Former les temps simples et composés à partir des bases verbales ; identifier temps et modes ; verbes pronominaux ; formes du participe passé (é, i, u, consonne finale)', page: 24 },
  { id: 'c4.fr.langue.passif', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A3, competence: 'Construire le passif et analyser ses effets de sens', page: 24 },
  { id: 'c4.fr.langue.temps-a-memoriser', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A3, competence: 'Mémoriser tous les temps de l’indicatif, le conditionnel présent et passé, l’impératif présent et le subjonctif pour être, avoir, les trois groupes et faire, aller, dire, venir, pouvoir, voir, vouloir, prendre, savoir, falloir, valoir', page: 24 },
  { id: 'c4.fr.langue.valeurs-des-temps', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A3, competence: 'Mettre en évidence le lien entre le temps employé et le sens : accompli et non accompli, premier plan et arrière-plan ; principaux emplois des modes', page: 24 },
  { id: 'c4.fr.langue.orthographe-lexicale', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A3, competence: 'Mémoriser l’orthographe des affixes et du lexique appris ; utiliser l’étymologie pour orthographier ; listes de fréquence', page: 24 },
  { id: 'c4.fr.langue.formation-des-mots', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A1, competence: 'Observer la formation des mots : dérivation, composition, étymologie, néologie, locutions ; sens des préfixes, des suffixes et de racines latines et grecques', page: 25 },
  { id: 'c4.fr.langue.reseaux-de-mots', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A1, competence: 'Mettre en réseau des mots : champ lexical, famille de mots, champ sémantique ; classer par degré d’intensité et de généralité', page: 25 },
  { id: 'c4.fr.langue.sens-des-mots', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A1, competence: 'Analyser le sens des mots : polysémie, synonymie, antonymie, homonymie, nuances et glissements de sens, dénotation et connotation, niveaux de langue', page: 25 },
  { id: 'c4.fr.langue.enonciation', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A1, competence: 'Identifier la situation d’énonciation (qui parle, à qui, où, quand) et les marques de personne, de lieu et de temps', page: 26 },
  { id: 'c4.fr.langue.coherence-textuelle', cycle: 4, discipline: 'french', domaine: 'c4-fr-langue', attendu: FR_A1, competence: 'Utiliser les marques d’organisation du texte (connecteurs, ponctuation), les reprises nominales et pronominales, les formes actives et passives', page: 26 },
  { id: 'c4.fr.culture.entrees', cycle: 4, discipline: 'french', domaine: 'c4-fr-culture', attendu: 'Lire au moins trois œuvres du patrimoine, trois œuvres en lecture cursive et trois groupements de textes par année', competence: 'Culture littéraire et artistique : se chercher, se construire ; vivre en société ; regarder le monde, inventer des mondes ; agir sur le monde', page: 27 },
  // ---------- Mathématiques ----------
  { id: 'c4.ma.a.relatifs', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A1, competence: 'Nombres décimaux relatifs, notion d’opposé ; comparer, ranger, encadrer ; repérer et placer sur une droite graduée', page: 130 },
  { id: 'c4.ma.a.calcul-relatifs', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A1, competence: 'Somme, différence, produit, quotient de nombres relatifs', page: 130 },
  { id: 'c4.ma.a.fractions', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A1, competence: 'Fractions et nombres rationnels ; égalité de fractions (ad = bc) ; comparer, ranger ; notion d’inverse', page: 130 },
  { id: 'c4.ma.a.calcul-fractions', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A1, competence: 'Somme, différence, produit, quotient de fractions', page: 131 },
  { id: 'c4.ma.a.ecritures-ordres-de-grandeur', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A1, competence: 'Passer d’une écriture d’un nombre à une autre (décimale, fractionnaire, scientifique) ; associer des ordres de grandeur à des objets', page: 130 },
  { id: 'c4.ma.a.puissances', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A1, competence: 'Puissances d’un nombre à exposant entier positif ou négatif ; puissances de 10 et notation scientifique ; préfixes de nano à giga', page: 130 },
  { id: 'c4.ma.a.carres-racine', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A1, competence: 'Carrés parfaits de 1 à 144 ; définition de la racine carrée, utilisée pour résoudre des problèmes, notamment géométriques', page: 130 },
  { id: 'c4.ma.a.divisibilite-premiers', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A2, competence: 'Multiples et diviseurs ; critères de divisibilité ; division euclidienne ; nombres premiers ; décomposition en facteurs premiers ; fraction irréductible', page: 131 },
  { id: 'c4.ma.a.reduire-developper', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A3, competence: 'Développer, factoriser, réduire des expressions littérales ; distributivité simple et double ; identité a² − b²', page: 131 },
  { id: 'c4.ma.a.equations', cycle: 4, discipline: 'maths', domaine: 'c4-ma-a', attendu: MA_A3, competence: 'Mettre un problème en équation ; résoudre des équations du premier degré, des équations produits et du type x² = a', page: 131 },
  { id: 'c4.ma.b.lire-donnees', cycle: 4, discipline: 'maths', domaine: 'c4-ma-b', attendu: MA_B1, competence: 'Lire et interpréter des données brutes, un tableau, un diagramme en bâtons, un diagramme circulaire ou un histogramme', page: 132 },
  { id: 'c4.ma.b.effectifs-frequences', cycle: 4, discipline: 'maths', domaine: 'c4-ma-b', attendu: MA_B1, competence: 'Recueillir et organiser des données ; calculer des effectifs et des fréquences', page: 132 },
  { id: 'c4.ma.b.indicateurs', cycle: 4, discipline: 'maths', domaine: 'c4-ma-b', attendu: MA_B1, competence: 'Calculer et interpréter la moyenne, la médiane et l’étendue d’une série statistique', page: 132 },
  { id: 'c4.ma.b.probabilites', cycle: 4, discipline: 'maths', domaine: 'c4-ma-b', attendu: MA_B2, competence: 'Probabilité d’un événement, entre 0 et 1 ; événements certains, impossibles, contraires ; calculer dans des cas simples ; lien entre fréquence et probabilité', page: 132 },
  { id: 'c4.ma.b.proportionnalite', cycle: 4, discipline: 'maths', domaine: 'c4-ma-b', attendu: MA_B3, competence: 'Reconnaître une situation de proportionnalité ou de non-proportionnalité ; coefficient ; calculer une quatrième proportionnelle', page: 133 },
  { id: 'c4.ma.b.pourcentages-echelles', cycle: 4, discipline: 'maths', domaine: 'c4-ma-b', attendu: MA_B3, competence: 'Pourcentages, taux d’évolution, coefficient multiplicateur ; échelles, agrandissement et réduction ; formules liant deux grandeurs (vitesse)', page: 133 },
  { id: 'c4.ma.b.ratio', cycle: 4, discipline: 'maths', domaine: 'c4-ma-b', attendu: MA_B3, competence: 'Notion de ratio ; partager une quantité en deux ou trois parts selon un ratio donné', page: 133 },
  { id: 'c4.ma.b.image-antecedent', cycle: 4, discipline: 'maths', domaine: 'c4-ma-b', attendu: MA_B4, competence: 'Vocabulaire des fonctions ; déterminer l’image ou un antécédent d’un nombre à partir d’une expression, d’un tableau de valeurs ou d’un graphique', page: 133 },
  { id: 'c4.ma.b.lineaire-affine', cycle: 4, discipline: 'maths', domaine: 'c4-ma-b', attendu: MA_B4, competence: 'Fonctions linéaire et affine : représentation graphique, coefficient directeur ; modéliser une situation de proportionnalité par une fonction linéaire', page: 133 },
  { id: 'c4.ma.c.grandeurs-composees', cycle: 4, discipline: 'maths', domaine: 'c4-ma-c', attendu: MA_C1, competence: 'Grandeurs produit et grandeurs quotient (vitesse, débit, masse volumique) ; vérifier la cohérence des unités', page: 134 },
  { id: 'c4.ma.c.aires-volumes', cycle: 4, discipline: 'maths', domaine: 'c4-ma-c', attendu: MA_C1, competence: 'Aire du parallélogramme ; volumes du prisme, de la pyramide, du cylindre, du cône et de la boule', page: 134 },
  { id: 'c4.ma.c.conversions', cycle: 4, discipline: 'maths', domaine: 'c4-ma-c', attendu: MA_C1, competence: 'Effectuer des conversions d’unités ; correspondance entre unités de volume et de contenance', page: 134 },
  { id: 'c4.ma.c.agrandissement', cycle: 4, discipline: 'maths', domaine: 'c4-ma-c', attendu: MA_C2, competence: 'Effet d’un agrandissement ou d’une réduction sur les longueurs, les angles, les aires et les volumes ; utiliser l’échelle d’une carte', page: 134 },
  { id: 'c4.ma.d.reperage', cycle: 4, discipline: 'maths', domaine: 'c4-ma-d', attendu: MA_D1, competence: 'Se repérer sur une droite graduée, dans un repère orthogonal, dans un pavé droit, sur une sphère (latitude, longitude)', page: 135 },
  { id: 'c4.ma.d.solides', cycle: 4, discipline: 'maths', domaine: 'c4-ma-d', attendu: MA_D1, competence: 'Reconnaître des solides et mettre en relation leurs représentations (perspective, vues, sections, patrons)', page: 135 },
  { id: 'c4.ma.d.angles-triangles', cycle: 4, discipline: 'maths', domaine: 'c4-ma-d', attendu: MA_D2, competence: 'Angles alternes-internes et correspondants ; somme des angles d’un triangle ; inégalité triangulaire ; hauteurs et médiatrices', page: 135 },
  { id: 'c4.ma.d.triangles-parallelogramme', cycle: 4, discipline: 'maths', domaine: 'c4-ma-d', attendu: MA_D2, competence: 'Cas d’égalité des triangles ; triangles semblables ; parallélogramme (définition et propriété caractéristique)', page: 135 },
  { id: 'c4.ma.d.thales', cycle: 4, discipline: 'maths', domaine: 'c4-ma-d', attendu: MA_D2, competence: 'Le théorème de Thalès et sa réciproque (triangles emboîtés, papillon)', page: 135 },
  { id: 'c4.ma.d.pythagore', cycle: 4, discipline: 'maths', domaine: 'c4-ma-d', attendu: MA_D2, competence: 'Le théorème de Pythagore et sa réciproque', page: 135 },
  { id: 'c4.ma.d.trigonometrie', cycle: 4, discipline: 'maths', domaine: 'c4-ma-d', attendu: MA_D2, competence: 'Lignes trigonométriques dans le triangle rectangle : cosinus, sinus, tangente', page: 135 },
  { id: 'c4.ma.d.transformations', cycle: 4, discipline: 'maths', domaine: 'c4-ma-d', attendu: MA_D2, competence: 'Comprendre l’effet d’une translation, d’une symétrie axiale ou centrale, d’une rotation, d’une homothétie sur une figure', page: 135 },
  { id: 'c4.ma.e.programmation', cycle: 4, discipline: 'maths', domaine: 'c4-ma-e', attendu: 'Écrire, mettre au point et exécuter un programme simple', competence: 'Algorithmique et programmation : variable, séquence d’instructions, boucle, instruction conditionnelle, événement', page: 136 },
  // ---------- Anglais (langues vivantes) ----------
  { id: 'c4.en.ecouter.intervention-breve', cycle: 4, discipline: 'english', domaine: 'c4-en-ecouter', attendu: LV_ECOUTER, competence: 'Comprendre les points essentiels d’un message oral simple ou d’une brève conversation ; identifier le sujet d’une conversation', page: 38 },
  { id: 'c4.en.ecouter.recit', cycle: 4, discipline: 'english', domaine: 'c4-en-ecouter', attendu: LV_ECOUTER, competence: 'Suivre le déroulement et l’intrigue d’un récit de fiction simple ; comprendre un message en continu sur un point d’intérêt personnel', page: 38 },
  { id: 'c4.en.ecouter.indices', cycle: 4, discipline: 'english', domaine: 'c4-en-ecouter', attendu: LV_ECOUTER, competence: 'Repérer des indices extralinguistiques et linguistiques (mots, expressions, schémas prosodiques) ; identifier la situation d’énonciation', page: 38 },
  { id: 'c4.en.lire.informations', cycle: 4, discipline: 'english', domaine: 'c4-en-lire', attendu: LV_LIRE, competence: 'Trouver des informations dans un texte sur une thématique connue ; repérer un renseignement dans un prospectus, un menu, une annonce, un horaire', page: 39 },
  { id: 'c4.en.lire.consignes-panneaux', cycle: 4, discipline: 'english', domaine: 'c4-en-lire', attendu: LV_LIRE, competence: 'Comprendre des consignes écrites, les signes et les panneaux courants, une lettre personnelle simple et brève', page: 39 },
  { id: 'c4.en.lire.recit', cycle: 4, discipline: 'english', domaine: 'c4-en-lire', attendu: LV_LIRE, competence: 'Saisir la trame narrative d’un récit clairement structuré ; mémoriser le lexique et les structures pour les reconnaître dans d’autres contextes', page: 39 },
  { id: 'c4.en.dialoguer.echanges-sociaux', cycle: 4, discipline: 'english', domaine: 'c4-en-dialoguer', attendu: LV_DIALOGUER, competence: 'Établir un contact social ; demander et donner des informations sur des sujets familiers, les besoins, la possession, l’heure, le prix, le temps qu’il fait', page: 40 },
  { id: 'c4.en.dialoguer.reagir', cycle: 4, discipline: 'english', domaine: 'c4-en-dialoguer', attendu: LV_DIALOGUER, competence: 'Réagir à des propositions et à des situations ; exprimer ses sentiments et réagir à des sentiments exprimés ; reformuler pour quelqu’un qui n’a pas compris', page: 40 },
  { id: 'c4.en.parler.presenter-raconter', cycle: 4, discipline: 'english', domaine: 'c4-en-parler', attendu: LV_PARLER, competence: 'Présenter, décrire, raconter, expliquer ; lire à haute voix de manière expressive ; exprimer son opinion personnelle', page: 41 },
  { id: 'c4.en.ecrire.dictee-fiche', cycle: 4, discipline: 'english', domaine: 'c4-en-ecrire', attendu: LV_ECRIRE, competence: 'Copier, écrire sous la dictée ; renseigner une fiche de renseignements ; écrire un message simple', page: 42 },
  { id: 'c4.en.ecrire.recit', cycle: 4, discipline: 'english', domaine: 'c4-en-ecrire', attendu: LV_ECRIRE, competence: 'Écrire un court récit, une description d’événement ou d’activités passées, des phrases reliées par des connecteurs', page: 42 },
  { id: 'c4.en.culture.langages', cycle: 4, discipline: 'english', domaine: 'c4-en-culture', attendu: LV_CULTURE, competence: 'Langages : codes socioculturels, médias et réseaux sociaux, langages artistiques (chansons, cinéma, littérature, bande dessinée)', page: 44 },
  { id: 'c4.en.culture.ecole-societe', cycle: 4, discipline: 'english', domaine: 'c4-en-culture', attendu: LV_CULTURE, competence: 'École et société : comparaison des systèmes scolaires, environnement, activités scolaires et extrascolaires, découverte du monde du travail', page: 44 },
  { id: 'c4.en.culture.voyages-rencontres', cycle: 4, discipline: 'english', domaine: 'c4-en-culture', attendu: LV_CULTURE, competence: 'Voyages et migrations ; rencontres avec d’autres cultures : repères historiques et géographiques, patrimoine', page: 44 },
  { id: 'c4.en.langue.lexique', cycle: 4, discipline: 'english', domaine: 'c4-en-langue', attendu: LV_LANGUE, competence: 'Lexique en lien avec les thèmes culturels et la vie quotidienne : mots isolés, expressions, sens des mots en contexte', page: 44 },
  { id: 'c4.en.langue.groupe-nominal', cycle: 4, discipline: 'english', domaine: 'c4-en-langue', attendu: LV_LANGUE, competence: 'Nom et groupe nominal : genre, pronoms personnels compléments et réfléchis ; détermination : articles, quantifieurs', page: 44 },
  { id: 'c4.en.langue.temps-verbaux', cycle: 4, discipline: 'english', domaine: 'c4-en-langue', attendu: LV_LANGUE, competence: 'Groupe verbal : expression du présent, du passé et de l’avenir ; construction des verbes', page: 44 },
  { id: 'c4.en.langue.modaux-passif', cycle: 4, discipline: 'english', domaine: 'c4-en-langue', attendu: LV_LANGUE, competence: 'Les modaux ; le passif', page: 44 },
  { id: 'c4.en.langue.phrase-complexe', cycle: 4, discipline: 'english', domaine: 'c4-en-langue', attendu: LV_LANGUE, competence: 'Énoncés simples et complexes : coordination, subordination, relatifs, discours indirect, interrogation indirecte, connecteurs', page: 44 },
  { id: 'c4.en.langue.phonologie', cycle: 4, discipline: 'english', domaine: 'c4-en-langue', attendu: LV_LANGUE, competence: 'Phonologie : régularités de la langue orale, variations ; viser la fluidité et l’intelligibilité, non l’accent natif', page: 44 },
  // ---------- Allemand (LV2, de la 5e à la 3e) : le programme de langues vivantes est commun à toutes les langues ----------
  { id: 'c4.de.ecouter.intervention-breve', cycle: 4, discipline: 'german', domaine: 'c4-de-ecouter', attendu: LV_ECOUTER, competence: 'Comprendre les points essentiels d’un message oral simple ou d’une brève conversation ; identifier le sujet d’une conversation', page: 38 },
  { id: 'c4.de.ecouter.recit', cycle: 4, discipline: 'german', domaine: 'c4-de-ecouter', attendu: LV_ECOUTER, competence: 'Suivre le déroulement et l’intrigue d’un récit de fiction simple ; comprendre un message en continu sur un point d’intérêt personnel', page: 38 },
  { id: 'c4.de.ecouter.indices', cycle: 4, discipline: 'german', domaine: 'c4-de-ecouter', attendu: LV_ECOUTER, competence: 'Repérer des indices extralinguistiques et linguistiques (mots, expressions, schémas prosodiques) ; identifier la situation d’énonciation', page: 38 },
  { id: 'c4.de.lire.informations', cycle: 4, discipline: 'german', domaine: 'c4-de-lire', attendu: LV_LIRE, competence: 'Trouver des informations dans un texte sur une thématique connue ; repérer un renseignement dans un prospectus, un menu, une annonce, un horaire', page: 39 },
  { id: 'c4.de.lire.consignes-panneaux', cycle: 4, discipline: 'german', domaine: 'c4-de-lire', attendu: LV_LIRE, competence: 'Comprendre des consignes écrites, les signes et les panneaux courants, une lettre personnelle simple et brève', page: 39 },
  { id: 'c4.de.lire.recit', cycle: 4, discipline: 'german', domaine: 'c4-de-lire', attendu: LV_LIRE, competence: 'Saisir la trame narrative d’un récit clairement structuré ; mémoriser le lexique et les structures pour les reconnaître dans d’autres contextes', page: 39 },
  { id: 'c4.de.dialoguer.echanges-sociaux', cycle: 4, discipline: 'german', domaine: 'c4-de-dialoguer', attendu: LV_DIALOGUER, competence: 'Établir un contact social ; demander et donner des informations sur des sujets familiers, les besoins, la possession, l’heure, le prix, le temps qu’il fait', page: 40 },
  { id: 'c4.de.dialoguer.reagir', cycle: 4, discipline: 'german', domaine: 'c4-de-dialoguer', attendu: LV_DIALOGUER, competence: 'Réagir à des propositions et à des situations ; exprimer ses sentiments et réagir à des sentiments exprimés ; reformuler pour quelqu’un qui n’a pas compris', page: 40 },
  { id: 'c4.de.parler.presenter-raconter', cycle: 4, discipline: 'german', domaine: 'c4-de-parler', attendu: LV_PARLER, competence: 'Présenter, décrire, raconter, expliquer ; lire à haute voix de manière expressive ; exprimer son opinion personnelle', page: 41 },
  { id: 'c4.de.ecrire.dictee-fiche', cycle: 4, discipline: 'german', domaine: 'c4-de-ecrire', attendu: LV_ECRIRE, competence: 'Copier, écrire sous la dictée ; renseigner une fiche de renseignements ; écrire un message simple', page: 42 },
  { id: 'c4.de.ecrire.recit', cycle: 4, discipline: 'german', domaine: 'c4-de-ecrire', attendu: LV_ECRIRE, competence: 'Écrire un court récit, une description d’événement ou d’activités passées, des phrases reliées par des connecteurs', page: 42 },
  { id: 'c4.de.culture.langages', cycle: 4, discipline: 'german', domaine: 'c4-de-culture', attendu: LV_CULTURE, competence: 'Langages : codes socioculturels, médias et réseaux sociaux, langages artistiques (chansons, cinéma, littérature, bande dessinée)', page: 44 },
  { id: 'c4.de.culture.ecole-societe', cycle: 4, discipline: 'german', domaine: 'c4-de-culture', attendu: LV_CULTURE, competence: 'École et société : comparaison des systèmes scolaires, environnement, activités scolaires et extrascolaires, découverte du monde du travail', page: 44 },
  { id: 'c4.de.culture.voyages-rencontres', cycle: 4, discipline: 'german', domaine: 'c4-de-culture', attendu: LV_CULTURE, competence: 'Voyages et migrations ; rencontres avec d’autres cultures : repères historiques et géographiques, patrimoine', page: 44 },
  { id: 'c4.de.langue.lexique', cycle: 4, discipline: 'german', domaine: 'c4-de-langue', attendu: LV_LANGUE, competence: 'Lexique en lien avec les thèmes culturels et la vie quotidienne : mots isolés, expressions, sens des mots en contexte', page: 44 },
  { id: 'c4.de.langue.groupe-nominal', cycle: 4, discipline: 'german', domaine: 'c4-de-langue', attendu: LV_LANGUE, competence: 'Nom et groupe nominal : genre, pronoms personnels compléments et réfléchis ; détermination : articles, quantifieurs', page: 44 },
  { id: 'c4.de.langue.temps-verbaux', cycle: 4, discipline: 'german', domaine: 'c4-de-langue', attendu: LV_LANGUE, competence: 'Groupe verbal : expression du présent, du passé et de l’avenir ; construction des verbes', page: 44 },
  { id: 'c4.de.langue.modaux-passif', cycle: 4, discipline: 'german', domaine: 'c4-de-langue', attendu: LV_LANGUE, competence: 'Les modaux ; le passif', page: 44 },
  { id: 'c4.de.langue.phrase-complexe', cycle: 4, discipline: 'german', domaine: 'c4-de-langue', attendu: LV_LANGUE, competence: 'Énoncés simples et complexes : coordination, subordination, relatifs, discours indirect, interrogation indirecte, connecteurs', page: 44 },
  { id: 'c4.de.langue.phonologie', cycle: 4, discipline: 'german', domaine: 'c4-de-langue', attendu: LV_LANGUE, competence: 'Phonologie : régularités de la langue orale, variations ; viser la fluidité et l’intelligibilité, non l’accent natif', page: 44 },
  // ---------- Espagnol (LV2, de la 5e à la 3e) ----------
  { id: 'c4.es.ecouter.intervention-breve', cycle: 4, discipline: 'spanish', domaine: 'c4-es-ecouter', attendu: LV_ECOUTER, competence: 'Comprendre les points essentiels d’un message oral simple ou d’une brève conversation ; identifier le sujet d’une conversation', page: 38 },
  { id: 'c4.es.ecouter.recit', cycle: 4, discipline: 'spanish', domaine: 'c4-es-ecouter', attendu: LV_ECOUTER, competence: 'Suivre le déroulement et l’intrigue d’un récit de fiction simple ; comprendre un message en continu sur un point d’intérêt personnel', page: 38 },
  { id: 'c4.es.ecouter.indices', cycle: 4, discipline: 'spanish', domaine: 'c4-es-ecouter', attendu: LV_ECOUTER, competence: 'Repérer des indices extralinguistiques et linguistiques (mots, expressions, schémas prosodiques) ; identifier la situation d’énonciation', page: 38 },
  { id: 'c4.es.lire.informations', cycle: 4, discipline: 'spanish', domaine: 'c4-es-lire', attendu: LV_LIRE, competence: 'Trouver des informations dans un texte sur une thématique connue ; repérer un renseignement dans un prospectus, un menu, une annonce, un horaire', page: 39 },
  { id: 'c4.es.lire.consignes-panneaux', cycle: 4, discipline: 'spanish', domaine: 'c4-es-lire', attendu: LV_LIRE, competence: 'Comprendre des consignes écrites, les signes et les panneaux courants, une lettre personnelle simple et brève', page: 39 },
  { id: 'c4.es.lire.recit', cycle: 4, discipline: 'spanish', domaine: 'c4-es-lire', attendu: LV_LIRE, competence: 'Saisir la trame narrative d’un récit clairement structuré ; mémoriser le lexique et les structures pour les reconnaître dans d’autres contextes', page: 39 },
  { id: 'c4.es.dialoguer.echanges-sociaux', cycle: 4, discipline: 'spanish', domaine: 'c4-es-dialoguer', attendu: LV_DIALOGUER, competence: 'Établir un contact social ; demander et donner des informations sur des sujets familiers, les besoins, la possession, l’heure, le prix, le temps qu’il fait', page: 40 },
  { id: 'c4.es.dialoguer.reagir', cycle: 4, discipline: 'spanish', domaine: 'c4-es-dialoguer', attendu: LV_DIALOGUER, competence: 'Réagir à des propositions et à des situations ; exprimer ses sentiments et réagir à des sentiments exprimés ; reformuler pour quelqu’un qui n’a pas compris', page: 40 },
  { id: 'c4.es.parler.presenter-raconter', cycle: 4, discipline: 'spanish', domaine: 'c4-es-parler', attendu: LV_PARLER, competence: 'Présenter, décrire, raconter, expliquer ; lire à haute voix de manière expressive ; exprimer son opinion personnelle', page: 41 },
  { id: 'c4.es.ecrire.dictee-fiche', cycle: 4, discipline: 'spanish', domaine: 'c4-es-ecrire', attendu: LV_ECRIRE, competence: 'Copier, écrire sous la dictée ; renseigner une fiche de renseignements ; écrire un message simple', page: 42 },
  { id: 'c4.es.ecrire.recit', cycle: 4, discipline: 'spanish', domaine: 'c4-es-ecrire', attendu: LV_ECRIRE, competence: 'Écrire un court récit, une description d’événement ou d’activités passées, des phrases reliées par des connecteurs', page: 42 },
  { id: 'c4.es.culture.langages', cycle: 4, discipline: 'spanish', domaine: 'c4-es-culture', attendu: LV_CULTURE, competence: 'Langages : codes socioculturels, médias et réseaux sociaux, langages artistiques (chansons, cinéma, littérature, bande dessinée)', page: 44 },
  { id: 'c4.es.culture.ecole-societe', cycle: 4, discipline: 'spanish', domaine: 'c4-es-culture', attendu: LV_CULTURE, competence: 'École et société : comparaison des systèmes scolaires, environnement, activités scolaires et extrascolaires, découverte du monde du travail', page: 44 },
  { id: 'c4.es.culture.voyages-rencontres', cycle: 4, discipline: 'spanish', domaine: 'c4-es-culture', attendu: LV_CULTURE, competence: 'Voyages et migrations ; rencontres avec d’autres cultures : repères historiques et géographiques, patrimoine', page: 44 },
  { id: 'c4.es.langue.lexique', cycle: 4, discipline: 'spanish', domaine: 'c4-es-langue', attendu: LV_LANGUE, competence: 'Lexique en lien avec les thèmes culturels et la vie quotidienne : mots isolés, expressions, sens des mots en contexte', page: 44 },
  { id: 'c4.es.langue.groupe-nominal', cycle: 4, discipline: 'spanish', domaine: 'c4-es-langue', attendu: LV_LANGUE, competence: 'Nom et groupe nominal : genre, pronoms personnels compléments et réfléchis ; détermination : articles, quantifieurs', page: 44 },
  { id: 'c4.es.langue.temps-verbaux', cycle: 4, discipline: 'spanish', domaine: 'c4-es-langue', attendu: LV_LANGUE, competence: 'Groupe verbal : expression du présent, du passé et de l’avenir ; construction des verbes', page: 44 },
  { id: 'c4.es.langue.modaux-passif', cycle: 4, discipline: 'spanish', domaine: 'c4-es-langue', attendu: LV_LANGUE, competence: 'Les modaux ; le passif', page: 44 },
  { id: 'c4.es.langue.phrase-complexe', cycle: 4, discipline: 'spanish', domaine: 'c4-es-langue', attendu: LV_LANGUE, competence: 'Énoncés simples et complexes : coordination, subordination, relatifs, discours indirect, interrogation indirecte, connecteurs', page: 44 },
  { id: 'c4.es.langue.phonologie', cycle: 4, discipline: 'spanish', domaine: 'c4-es-langue', attendu: LV_LANGUE, competence: 'Phonologie : régularités de la langue orale, variations ; viser la fluidité et l’intelligibilité, non l’accent natif', page: 44 },
  // ---------- Histoire et géographie (5e, 4e, 3e) ----------
  { id: 'c4.hg.temps.reperes', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-temps', attendu: HG_TEMPS, competence: 'Situer un fait dans une époque ou une période donnée ; mettre en relation des faits d’une époque ou d’une période donnée', page: 78 },
  { id: 'c4.hg.temps.ordonner', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-temps', attendu: HG_TEMPS, competence: 'Ordonner des faits les uns par rapport aux autres ; identifier des continuités et des ruptures chronologiques pour s’approprier la périodisation de l’histoire', page: 78 },
  { id: 'c4.hg.espace.localiser', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-espace', attendu: HG_ESPACE, competence: 'Nommer et localiser les grands repères géographiques ; nommer, localiser et caractériser un lieu dans un espace géographique et des espaces plus complexes', page: 79 },
  { id: 'c4.hg.espace.situer', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-espace', attendu: HG_ESPACE, competence: 'Situer des lieux et des espaces les uns par rapport aux autres ; utiliser des représentations analogiques et numériques des espaces à différentes échelles ainsi que différents modes de projection', page: 79 },
  { id: 'c4.hg.demarches.document', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-demarches', attendu: HG_DOC, competence: 'Comprendre le sens général d’un document ; identifier le document ; extraire des informations pertinentes pour répondre à une question portant sur un ou plusieurs documents, les classer, les hiérarchiser', page: 79 },
  { id: 'c4.hg.demarches.point-de-vue', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-demarches', attendu: HG_DOC, competence: 'Identifier le point de vue particulier d’un document ; le confronter à ce qu’on peut connaître par ailleurs du sujet étudié ; utiliser ses connaissances pour l’expliquer et exercer son esprit critique', page: 79 },
  { id: 'c4.hg.demarches.lexique', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-demarches', attendu: HG_LANGAGES, competence: 'S’approprier et utiliser un lexique spécifique en contexte', page: 79 },
  { id: 'c4.hg.demarches.cartes', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-demarches', attendu: HG_LANGAGES, competence: 'Réaliser des productions graphiques et cartographiques', page: 79 },
  { id: 'c4.hg.demarches.ecrire-dire', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-demarches', attendu: HG_LANGAGES, competence: 'Écrire pour construire sa pensée et son savoir, pour argumenter et pour communiquer ; s’exprimer à l’oral ; connaître les caractéristiques des récits historiques et en réaliser ; réaliser une production audiovisuelle, un diaporama', page: 79 },
  { id: 'c4.hg.demarches.raisonner', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-demarches', attendu: HG_RAISONNER, competence: 'Poser et se poser des questions ; construire des hypothèses d’interprétation ; vérifier des données et des sources ; justifier une démarche, une interprétation', page: 79 },
  { id: 'c4.hg.histoire.chretientes-islam', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-histoire', attendu: HG_5H, competence: 'Thème 1 : Chrétientés et islam (VIe-XIIIe siècles), des mondes en contact ; Byzance et l’Europe carolingienne ; de la naissance de l’islam à la prise de Bagdad par les Mongols : pouvoirs, sociétés, cultures', page: 81 },
  { id: 'c4.hg.histoire.occident-feodal', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-histoire', attendu: HG_5H, competence: 'Thème 2 : Société, Église et pouvoir politique dans l’Occident féodal (XIe-XVe siècles) ; l’ordre seigneurial et les campagnes ; l’émergence d’une société urbaine ; l’affirmation de l’État monarchique des Capétiens et des Valois', page: 81 },
  { id: 'c4.hg.histoire.europe-xvie-xviie', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-histoire', attendu: HG_5H, competence: 'Thème 3 : Transformations de l’Europe et ouverture sur le monde aux XVIe et XVIIe siècles ; le monde au temps de Charles Quint et de Soliman le Magnifique ; humanisme, réformes et conflits religieux ; du prince de la Renaissance au roi absolu', page: 82 },
  { id: 'c4.hg.histoire.xviiie-revolutions', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-histoire', attendu: HG_4H, competence: 'Thème 1 : Le XVIIIe siècle. Expansions, Lumières et révolutions ; bourgeoisies marchandes, négoces internationaux, traites négrières et esclavage ; l’Europe des Lumières ; la Révolution française et l’Empire', page: 82 },
  { id: 'c4.hg.histoire.europe-monde-xixe', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-histoire', attendu: HG_4H, competence: 'Thème 2 : L’Europe et le monde au XIXe siècle ; l’Europe de la « révolution industrielle » ; conquêtes et sociétés coloniales', page: 83 },
  { id: 'c4.hg.histoire.france-xixe', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-histoire', attendu: HG_4H, competence: 'Thème 3 : Société, culture et politique dans la France du XIXe siècle ; une difficile conquête : voter de 1815 à 1870 ; la Troisième République ; conditions féminines dans une société en mutation', page: 83 },
  { id: 'c4.hg.histoire.guerres-totales', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-histoire', attendu: HG_3H, competence: 'Thème 1 : L’Europe, un théâtre majeur des guerres totales (1914-1945) ; civils et militaires dans la Première Guerre mondiale ; démocraties fragilisées et expériences totalitaires ; la Deuxième Guerre mondiale, une guerre d’anéantissement ; la France défaite et occupée', page: 83 },
  { id: 'c4.hg.histoire.monde-depuis-1945', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-histoire', attendu: HG_3H, competence: 'Thème 2 : Le monde depuis 1945 ; indépendances et construction de nouveaux États ; un monde bipolaire au temps de la guerre froide ; le projet européen ; enjeux et conflits dans le monde après 1989', page: 84 },
  { id: 'c4.hg.histoire.republique-repensee', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-histoire', attendu: HG_3H, competence: 'Thème 3 : Françaises et Français dans une République repensée ; 1944-1947, refonder la République ; la Ve République, de la République gaullienne à l’alternance et à la cohabitation ; femmes et hommes dans la société des années 1950 aux années 1980', page: 84 },
  { id: 'c4.hg.geographie.demographie-developpement', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-geographie', attendu: HG_5G, competence: 'Thème 1 : La question démographique et l’inégal développement ; la croissance démographique et ses effets ; la répartition de la richesse et de la pauvreté dans le monde', page: 86 },
  { id: 'c4.hg.geographie.ressources', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-geographie', attendu: HG_5G, competence: 'Thème 2 : Des ressources limitées, à gérer et à renouveler ; l’énergie, l’eau : des ressources à ménager et à mieux utiliser ; l’alimentation : nourrir une humanité en croissance', page: 86 },
  { id: 'c4.hg.geographie.risques-changement-global', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-geographie', attendu: HG_5G, competence: 'Thème 3 : L’environnement, du local au planétaire ; le changement global climatique et ses principaux effets géographiques régionaux ; prévenir et s’adapter aux risques (industriels, technologiques et sanitaires ou liés au changement climatique)', page: 87 },
  { id: 'c4.hg.geographie.urbanisation', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-geographie', attendu: HG_4G, competence: 'Thème 1 : L’urbanisation du monde ; espaces et paysages de l’urbanisation : centres et périphéries ; des villes inégalement connectées aux réseaux de la mondialisation', page: 88 },
  { id: 'c4.hg.geographie.mobilites', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-geographie', attendu: HG_4G, competence: 'Thème 2 : Les mobilités humaines transnationales ; un monde de migrants ; le tourisme et ses espaces', page: 88 },
  { id: 'c4.hg.geographie.mondialisation', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-geographie', attendu: HG_4G, competence: 'Thème 3 : Des espaces transformés par la mondialisation ; mers et océans : un monde maritimisé ; l’adaptation du territoire des États-Unis ; les dynamiques d’un grand ensemble géographique africain', page: 89 },
  { id: 'c4.hg.geographie.dynamiques-france', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-geographie', attendu: HG_3G, competence: 'Thème 1 : Dynamiques territoriales de la France contemporaine ; les aires urbaines ; les espaces productifs et leurs évolutions ; les espaces de faible densité et leurs atouts', page: 89 },
  { id: 'c4.hg.geographie.amenager', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-geographie', attendu: HG_3G, competence: 'Thème 2 : Pourquoi et comment aménager le territoire ? Aménager pour répondre aux inégalités entre territoires, à toutes les échelles ; les territoires ultramarins français, une problématique spécifique', page: 90 },
  { id: 'c4.hg.geographie.france-ue', cycle: 4, discipline: 'history-geography', domaine: 'c4-hg-geographie', attendu: HG_3G, competence: 'Thème 3 : La France et l’Union européenne ; l’Union européenne, un nouveau territoire de référence et d’appartenance ; la France et l’Europe dans le monde', page: 90 },
  // ---------- Physique-chimie (5e, 4e, 3e ; libellés et pages à vérifier) ----------
  { id: 'c4.pc.demarches.experimenter', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-demarches', attendu: ST_DEMARCHE, competence: 'Identifier une question scientifique ; formuler une hypothèse ; proposer une expérience pour la tester ; interpréter les résultats et conclure', page: 100, unverified: true },
  { id: 'c4.pc.demarches.manipuler', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-demarches', attendu: ST_OUTILS, competence: 'Mettre en œuvre un protocole expérimental : réaliser un montage, manipuler, mesurer, en respectant les règles de sécurité', page: 100, unverified: true },
  { id: 'c4.pc.demarches.langages', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-demarches', attendu: ST_LANGAGES, competence: 'Lire et exploiter des données (tableau, graphique, schéma) ; passer d’un langage à un autre ; utiliser les unités et les ordres de grandeur', page: 101, unverified: true },
  { id: 'c4.pc.matiere.etats', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-matiere', attendu: PC_CONSTITUTION, competence: 'États de la matière et changements d’état ; masse et volume, masse volumique ; corps purs et mélanges ; solubilité et miscibilité', page: 102, unverified: true },
  { id: 'c4.pc.matiere.transformations', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-matiere', attendu: PC_TRANSFORMATIONS, competence: 'Distinguer transformation chimique et mélange ou changement d’état ; réactifs et produits ; redistribution des atomes et conservation de la masse ; l’équation de réaction', page: 103, unverified: true },
  { id: 'c4.pc.matiere.acides-bases', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-matiere', attendu: PC_TRANSFORMATIONS, competence: 'Solutions acides, neutres et basiques : le pH, les ions hydrogène et hydroxyde ; les précautions à prendre', page: 103, unverified: true },
  { id: 'c4.pc.matiere.univers', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-matiere', attendu: PC_UNIVERS, competence: 'La structure de l’Univers et du système solaire ; l’année-lumière et les ordres de grandeur des distances ; atomes, noyau et électrons ; les éléments formés dans les étoiles', page: 104, unverified: true },
  { id: 'c4.pc.mouvement.decrire', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-mouvement', attendu: PC_MOUVEMENT, competence: 'Décrire un mouvement par rapport à un objet de référence : trajectoire, vitesse (direction, sens, valeur) ; mouvement uniforme, accéléré, ralenti ; calculer une vitesse', page: 105, unverified: true },
  { id: 'c4.pc.mouvement.forces', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-mouvement', attendu: PC_FORCE, competence: 'Les actions mécaniques et leur modélisation par une force ; le poids et la masse ; la gravitation', page: 105, unverified: true },
  { id: 'c4.pc.energie.formes', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-energie', attendu: PC_ENERGIE, competence: 'Les formes d’énergie (cinétique, de position, thermique, électrique, chimique, nucléaire, lumineuse) ; sources, transferts, conversions ; puissance et énergie, le kilowattheure', page: 106, unverified: true },
  { id: 'c4.pc.energie.circuits', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-energie', attendu: PC_ELECTRICITE, competence: 'Circuits en série et en dérivation ; intensité et tension, leurs lois ; la loi d’Ohm ; la puissance électrique ; les règles de sécurité électrique', page: 107, unverified: true },
  { id: 'c4.pc.signaux.lumiere-son', cycle: 4, discipline: 'physics-chemistry', domaine: 'c4-pc-signaux', attendu: PC_SIGNAUX, competence: 'La lumière se propage en ligne droite, sa vitesse ; le son a besoin d’un milieu matériel, sa vitesse ; fréquence et hauteur d’un son, infrasons et ultrasons ; le niveau sonore et ses dangers', page: 108, unverified: true },
  // ---------- SVT (5e, 4e, 3e ; libellés et pages à vérifier) ----------
  { id: 'c4.sv.demarches.raisonner', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-demarches', attendu: ST_DEMARCHE, competence: 'Formuler une question ou un problème scientifique ; proposer des hypothèses ; concevoir une expérience pour les tester ; interpréter des résultats et argumenter', page: 110, unverified: true },
  { id: 'c4.sv.demarches.manipuler', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-demarches', attendu: ST_OUTILS, competence: 'Observer au microscope, disséquer, faire une culture, un prélèvement ou une sortie sur le terrain', page: 110, unverified: true },
  { id: 'c4.sv.demarches.langages', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-demarches', attendu: ST_LANGAGES, competence: 'Lire et exploiter des données (tableau, graphique, schéma, carte) ; les représenter sous une autre forme ; utiliser le vocabulaire scientifique', page: 111, unverified: true },
  { id: 'c4.sv.terre.geologie', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-terre', attendu: SV_GEOLOGIE, competence: 'La Terre, planète active : structure du globe, tectonique des plaques, séismes et volcans ; érosion et formation des roches ; les risques sismiques et volcaniques', page: 112, unverified: true },
  { id: 'c4.sv.terre.climat', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-terre', attendu: SV_CLIMAT, competence: 'Les mouvements des masses d’air et d’eau ; distinguer météo et climat ; les changements climatiques passés et actuels ; les risques météorologiques et leur prévention', page: 113, unverified: true },
  { id: 'c4.sv.terre.action-humaine', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-terre', attendu: SV_ACTION, competence: 'L’exploitation des ressources (eau, sols, roches, énergies fossiles, ressources de la mer) ; l’action humaine sur les écosystèmes ; les comportements responsables', page: 114, unverified: true },
  { id: 'c4.sv.vivant.nutrition', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-vivant', attendu: SV_VIVANT, competence: 'La cellule, unité du vivant ; la nutrition des végétaux et des animaux, les échanges avec le milieu ; la photosynthèse', page: 115, unverified: true },
  { id: 'c4.sv.vivant.genetique', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-vivant', attendu: SV_CAUSALITE, competence: 'Reproduction sexuée et asexuée ; chromosomes, gènes et ADN ; l’unicité génétique de chaque individu ; la dynamique des populations', page: 116, unverified: true },
  { id: 'c4.sv.vivant.evolution', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-vivant', attendu: SV_CAUSALITE, competence: 'La biodiversité et ses changements ; la classification par les liens de parenté ; l’évolution des espèces : variation, sélection naturelle', page: 116, unverified: true },
  { id: 'c4.sv.corps.effort-nerveux', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-corps', attendu: SV_CORPS, competence: 'L’effort physique : muscles, cœur, respiration ; le système nerveux et le cerveau ; les effets du sommeil, des écrans et des drogues', page: 117, unverified: true },
  { id: 'c4.sv.corps.digestion-microbes', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-corps', attendu: SV_CORPS, competence: 'Alimentation et digestion ; le monde microbien, le microbiote ; infections et défenses de l’organisme ; vaccination, antiseptiques, antibiotiques', page: 118, unverified: true },
  { id: 'c4.sv.corps.reproduction', cycle: 4, discipline: 'life-earth-sciences', domaine: 'c4-sv-corps', attendu: SV_CORPS, competence: 'La puberté ; la reproduction humaine ; la contraception et une sexualité responsable', page: 118, unverified: true },
  // ---------- Technologie (5e, 4e, 3e ; libellés et pages à vérifier) ----------
  { id: 'c4.te.demarches.langages', cycle: 4, discipline: 'technology', domaine: 'c4-te-demarches', attendu: ST_LANGAGES, competence: 'Lire et produire des représentations : croquis, schéma, carte mentale, diagramme, représentation numérique ; utiliser le vocabulaire technique', page: 120, unverified: true },
  { id: 'c4.te.demarches.responsable', cycle: 4, discipline: 'technology', domaine: 'c4-te-demarches', attendu: ST_RESPONSABLE, competence: 'Mesurer l’impact d’un objet sur l’environnement et la société : cycle de vie, consommation d’énergie, recyclage', page: 121, unverified: true },
  { id: 'c4.te.design.besoin', cycle: 4, discipline: 'technology', domaine: 'c4-te-design', attendu: TE_DESIGN, competence: 'Identifier un besoin et énoncer un problème technique ; s’approprier un cahier des charges : fonctions, contraintes, normes', page: 122, unverified: true },
  { id: 'c4.te.design.solutions', cycle: 4, discipline: 'technology', domaine: 'c4-te-design', attendu: TE_DESIGN, competence: 'Imaginer des solutions ; associer des solutions techniques à des fonctions ; choisir une solution selon les critères du cahier des charges', page: 122, unverified: true },
  { id: 'c4.te.design.prototype', cycle: 4, discipline: 'technology', domaine: 'c4-te-design', attendu: TE_PROJET, competence: 'Réaliser en équipe le prototype de tout ou partie d’un objet pour valider une solution ; organiser un projet', page: 122, unverified: true },
  { id: 'c4.te.objets.evolution', cycle: 4, discipline: 'technology', domaine: 'c4-te-objets', attendu: TE_OBJETS, competence: 'L’évolution des objets et des systèmes : contexte, progrès techniques, changements dans la société ; les objets communicants et leurs bonnes pratiques (données personnelles)', page: 123, unverified: true },
  { id: 'c4.te.modelisation.fonctionnement', cycle: 4, discipline: 'technology', domaine: 'c4-te-modelisation', attendu: TE_ANALYSER, competence: 'Fonctions et structure d’un objet ; chaîne d’énergie et chaîne d’information : capteurs, actionneurs, transmission du mouvement ; les matériaux et leurs propriétés', page: 124, unverified: true },
  { id: 'c4.te.modelisation.simuler', cycle: 4, discipline: 'technology', domaine: 'c4-te-modelisation', attendu: TE_SIMULER, competence: 'Lire une modélisation, interpréter le résultat d’une simulation (courbe, tableau) et le comparer aux exigences du cahier des charges', page: 125, unverified: true },
  { id: 'c4.te.informatique.reseaux', cycle: 4, discipline: 'technology', domaine: 'c4-te-informatique', attendu: TE_RESEAU, competence: 'Le réseau informatique : ses composants, l’adresse d’un appareil, les protocoles ; internet et le stockage des données', page: 126, unverified: true },
  { id: 'c4.te.informatique.programmer', cycle: 4, discipline: 'technology', domaine: 'c4-te-informatique', attendu: TE_PROGRAMMER, competence: 'Écrire, mettre au point et exécuter un programme qui commande un système réel : séquences, boucles, conditions, variables, événements', page: 126, unverified: true },
] as const satisfies readonly ProgrammeEntry[];
