import { Engine } from '@babylonjs/core/Engines/engine.js';
import { Scene } from '@babylonjs/core/scene.js';
import { Mesh } from '@babylonjs/core/Meshes/mesh.js';
import { VertexData } from '@babylonjs/core/Meshes/mesh.vertexData.js';
import { SubMesh } from '@babylonjs/core/Meshes/subMesh.js';
import '@babylonjs/core/Meshes/thinInstanceMesh.js';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial.js';
import { MultiMaterial } from '@babylonjs/core/Materials/multiMaterial.js';
import { Texture } from '@babylonjs/core/Materials/Textures/texture.js';
import { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight.js';
import { DirectionalLight } from '@babylonjs/core/Lights/directionalLight.js';
import { UniversalCamera } from '@babylonjs/core/Cameras/universalCamera.js';
import { Vector3 } from '@babylonjs/core/Maths/math.vector.js';
import { Color4 } from '@babylonjs/core/Maths/math.color.js';
const e = new Engine(document.querySelector('canvas')); const s = new Scene(e); s.clearColor = new Color4(); s.fogMode = Scene.FOGMODE_LINEAR;
const m = new Mesh('m', s); const v = new VertexData(); v.positions = new Float32Array(9); v.indices = [0, 1, 2]; v.applyToMesh(m);
const sm = new StandardMaterial('s', s); sm.diffuseTexture = new Texture('', s); m.material = new MultiMaterial('mm', s); SubMesh.CreateFromIndices(0, 0, 3, m);
m.thinInstanceSetBuffer('matrix', new Float32Array(16), 16);
new HemisphericLight('h', Vector3.Up(), s); new DirectionalLight('d', Vector3.Down(), s); new UniversalCamera('c', Vector3.Zero(), s);
e.runRenderLoop(() => s.render());
