import {
  ArrowLeft,
  Blocks,
  BookOpen,
  Calculator,
  Castle,
  Check,
  CircleHelp,
  Compass,
  Crown,
  Dumbbell,
  Flag,
  Flame,
  Footprints,
  Gem,
  Hammer,
  House,
  Library,
  Lightbulb,
  Lock,
  Map,
  Medal,
  Mountain,
  Pickaxe,
  Pizza,
  Play,
  RotateCcw,
  Ruler,
  Settings,
  Shuffle,
  Moon,
  Sparkles,
  Sun,
  Square,
  Star,
  Target,
  TreePine,
  Trophy,
  Volume2,
  VolumeX,
  Wheat,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const ICONS = {
  back: ArrowLeft,
  blocks: Blocks,
  book: BookOpen,
  calculator: Calculator,
  castle: Castle,
  check: Check,
  help: CircleHelp,
  close: X,
  compass: Compass,
  hammer: Hammer,
  map: Map,
  pickaxe: Pickaxe,
  sparkles: Sparkles,
  tree: TreePine,
  wheat: Wheat,
  crown: Crown,
  dumbbell: Dumbbell,
  flag: Flag,
  flame: Flame,
  footprints: Footprints,
  gem: Gem,
  home: House,
  library: Library,
  lightbulb: Lightbulb,
  lock: Lock,
  medal: Medal,
  mountain: Mountain,
  pizza: Pizza,
  play: Play,
  replay: RotateCcw,
  ruler: Ruler,
  settings: Settings,
  shuffle: Shuffle,
  stop: Square,
  speaker: Volume2,
  star: Star,
  target: Target,
  trophy: Trophy,
  sun: Sun,
  moon: Moon,
  volume: Volume2,
  volumeOff: VolumeX,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type AnyIconName = keyof typeof ICONS;

interface Props {
  name: AnyIconName;
  size?: number | string;
  className?: string;
}

/** Icône décorative (masquée aux lecteurs d'écran : le texte voisin porte le sens). */
export function Icon({ name, size = '1.2em', className }: Props) {
  const Component = ICONS[name];
  return <Component size={size} strokeWidth={2.5} className={className} aria-hidden="true" focusable="false" />;
}
